---
- name: NodeJS ppa key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
- name: NodeJS ppa
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_8.x xenial main'
- name: Update apt cache
  apt:
    name: nodejs
    update_cache: yes
- name: eWaterCycle/TerriaMap repo
  git:
    repo: https://github.com/eWaterCycle/TerriaMap.git
    dest: /mnt/apps/TerriaMap
    version: "{{ terriamap_version }}"
    force: yes
  notify:
    - restart terriamap
- name: Yarn
  npm:
    name: yarn
    global: yes
- name: TerriaMap/packages dir
  file:
    path: /mnt/apps/TerriaMap/packages
    state: directory
- name: eWaterCycle/terriajs repo
  git:
    repo: https://github.com/eWaterCycle/terriajs.git
    dest: /mnt/apps/TerriaMap/packages/terriajs
    version: "{{ terriajs_version }}"
    force: yes
  notify:
    - restart terriamap
- name: Install TerriaMap dependencies
  yarn:
    path: /mnt/apps/TerriaMap
- name: eWaterCycle/terriajs build
  command: npm run gulp
  args:
    chdir: /mnt/apps/TerriaMap/packages/terriajs
- name: eWaterCycle/TerriaMap build
  command: npm run gulp
  args:
    chdir: /mnt/apps/TerriaMap
- name: eWaterCycle/TerriaMap systemd
  copy:
    src: terriamap.systemd
    dest: /etc/systemd/system/terriamap.service
- name: TerriaMap server deps
  apt:
    name: gdal-bin
- name: eWaterCycle/TerriaMap started & enabled
  systemd:
    name: terriamap
    state: started
    daemon_reload: yes
    enabled: yes
- name: Inject launcher url
  command: perl -pi -e 's!https://hub\.ewatercycle2-nlesc\.surf-hosted\.nl:8888!{{ launcher_url }}!' /mnt/apps/TerriaMap/wwwroot/build/TerriaMap.js
- name: Inject Jupyter Hub url
  command: perl -pi -e 's!https://hub\.ewatercycle2-nlesc\.surf-hosted\.nl!{{ jupyterhub_url }}!' /mnt/apps/TerriaMap/wwwroot/build/TerriaMap.js
