---
- name: NodeJS ppa key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
- name: NodeJS ppa
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_10.x focal main'
- name: Update apt cache
  apt:
    name: nodejs
    update_cache: yes
- name: eWaterCycle/TerriaMap repo
  git:
    repo: https://github.com/eWaterCycle/TerriaMap.git
    dest: /mnt/apps/TerriaMap
    version: "{{ terriamap_version }}"
    force: yes
  notify:
    - Restart terriamap
    - Clean terriamap build
- name: Yarn
  npm:
    name: yarn
    global: yes
- name: TerriaMap/packages dir
  file:
    path: /mnt/apps/TerriaMap/packages
    state: directory
    mode: 0755
- name: eWaterCycle/TerriaMap systemd
  copy:
    src: terriamap.systemd
    dest: /etc/systemd/system/terriamap.service
    mode: 0644
- name: eWaterCycle/TerriaMap started & enabled
  systemd:
    name: terriamap
    state: started
    daemon_reload: yes
    enabled: yes
- name: Flush handlers
  meta: flush_handlers
- name: TerriaMap server deps
  apt:
    name: gdal-bin
- name: eWaterCycle/terriajs repo
  git:
    repo: https://github.com/eWaterCycle/terriajs.git
    dest: /mnt/apps/TerriaMap/packages/terriajs
    version: "{{ terriajs_version }}"
    force: yes
  notify:
    - Restart terriamap
    - Clean terriajs build
- name: Install TerriaMap dependencies
  yarn:
    path: /mnt/apps/TerriaMap
- name: eWaterCycle/terriajs build
  command: /usr/bin/npm run gulp build
  args:
    chdir: /mnt/apps/TerriaMap/packages/terriajs
    creates: /mnt/apps/TerriaMap/packages/terriajs/wwwroot/build
- name: eWaterCycle/TerriaMap build
  command: /usr/bin/npm run gulp
  args:
    chdir: /mnt/apps/TerriaMap
    creates: /mnt/apps/TerriaMap/wwwroot/build
- name: Inject launcher url
  command: >  # noqa 301 file will not be changed when OK
    perl -pi -e
     's!https://hub\.ewatercycle2-nlesc\.surf-hosted\.nl:8888!{{ launcher_url }}!'
     /mnt/apps/TerriaMap/wwwroot/build/TerriaMap.js
- name: Inject Jupyter Hub url
  command: > # noqa 301 file will not be changed when OK
   perl -pi -e
    's!https://hub\.ewatercycle2-nlesc\.surf-hosted\.nl!{{ jupyterhub_url }}!'
    /mnt/apps/TerriaMap/wwwroot/build/TerriaMap.js
- name: Flush handlers
  meta: flush_handlers
- name: Nginx config root
  file:
    path: /etc/nginx/app-location-conf.d
    state: directory
    mode: 0755
- name: Create nginx location block
  copy:
    dest: /etc/nginx/app-location-conf.d/explore.conf
    mode: 0644
    content: |
      location / {
          proxy_pass http://127.0.0.1:3001;
          proxy_redirect http://localhost:3001/ $scheme://$host/;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $connection_upgrade;
          client_max_body_size 10G;
      }
