---
- name: Singularity build dir
  file:
    path: /root/go/src/github.com/hpcng
    state: directory
- name: Clone experiment-launcher repo
  git:
    repo:  https://github.com/hpcng/singularity.git
    dest: /root/go/src/github.com/hpcng/singularity
    version: "v{{ singularity_version }}"
- name: Go dependencies
  command: go get -u -v github.com/golang/dep/cmd/dep
  args:
    chdir: /root/go/src/github.com/hpcng/singularity
    creates: /root/go/bin/dep
  environment:
    GOPATH: /root/go
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/go/bin
    GO111MODULE: 'off'
- name: mconfig
  command: ./mconfig --sysconfdir=/etc
  args:
    chdir: /root/go/src/github.com/hpcng/singularity
    creates: /root/go/src/github.com/hpcng/singularity/builddir
  environment:
    GOPATH: /root/go
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/go/bin
- name: Make
  make:
    chdir: /root/go/src/github.com/hpcng/singularity/builddir
  environment:
    GOPATH: /root/go
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/go/bin
- name: Make install
  make:
    target: install
    chdir: /root/go/src/github.com/hpcng/singularity/builddir
  environment:
    GOPATH: /root/go
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/go/bin
