---
- name: Fetch Go binary tarball
  get_url:
    url: https://dl.google.com/go/go{{ go_version }}.linux-amd64.tar.gz
    dest: /mnt/apps
    checksum: sha256:{{ go_sha256sum }}
- name: Unarchive Go binary tarball
  unarchive:
    src: /mnt/apps/go{{ go_version }}.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes
