---
- name: system dependencies
  apt:
    name:
      - build-essential
      - libssl-dev
      - uuid-dev
      - libgpgme11-dev
      - squashfs-tools
      - cryptsetup-bin
- name: Get Go
  include: go.yml
- name: Build singularity
  include: build.yml
