---
- name: system dependencies
  apt:
    name:
      - build-essential
      - libssl-dev
      - uuid-dev
      - libgpgme11-dev
      - squashfs-tools
      - cryptsetup-bin
- name: Install singularity deb binary 
  ansible.builtin.apt:
    deb: https://github.com/apptainer/singularity/releases/download/v{{ singularity_version }}/singularity-container_{{ singularity_version }}_amd64.deb
