---
- name: system dependencies
  apt:
    name:
      - build-essential
      - libssl-dev
      - uuid-dev
      - libgpgme11-dev
      - squashfs-tools
      - cryptsetup-bin
- name: Get Go
  include: go.yml
- name: Build singularity
  include: build.yml
- name: Reclaim disk space
  file:
    path: '{{ item }}'
    state: absent
  loop:
    - ~root/go/
    - /mnt/apps/go{{ go_version }}.linux-amd64.tar.gz
