---
- name: system dependencies
  apt:
    name: '{{ item }}'
  loop:
    - build-essential
    - libssl-dev
    - uuid-dev
    - libgpgme11-dev
    - squashfs-tools
- name: Get Go
  include: go.yml
- name: Build singularity
  include: build.yml
