---
- name: nginx light
  apt:
    name: nginx-light
- name: Copy nginx config
  template:
    src: nginx-default.j2
    dest: /etc/nginx/sites-available/default
  notify:
    - restart nginx
- name: Stop nginx before renewing cert
  copy:
    src: nginx-stop.sh
    dest: /etc/letsencrypt/renewal-hooks/pre/nginx-stop.sh
    mode: 0755
- name: Start nginx after renewing cert
  copy:
    src: nginx-start.sh
    dest: /etc/letsencrypt/renewal-hooks/post/nginx-start.sh
    mode: 0755
