---
- hosts: explore
  tasks:
    - include_role:
        name: common
    - include_role:
        name: letsencrypt
    - include_role:
        name: launcher
    - include_role:
        name: terria
    - include_role:
        name: reverse-proxy
      vars:
        locations:
          - name: /launcher
            proxy_pass: http://localhost:8888/
          - name: /
            proxy_pass: http://localhost:3001/
