---
- hosts: forecast
  tasks:
    - include_role:
        name: common
    - name: Install git, ntp and pip
      apt:
        update_cache: yes
        name: "{{ item }}"
      loop:
        - git
        - ntp
        - apt-transport-https
    - name: Home root
      file:
        path: /mnt/home
        state: directory
    - name: Apps root
      file:
        path: /mnt/apps
        state: directory
- hosts: forecast
  tasks:
    - name: Letsencrypt
      include_role:
        name: letsencrypt
    - name: Docker
      include_role:
        name: docker
      vars:
        - docker_root: "/mnt/docker"
    - name: Forecast Web
      include_role:
        name: forecast-web
    - name: Researchdrive
      include_role:
        name: researchdrive
      vars:
          researchdrive_src_dir: "{{ researchdrive.remote_dir }}"
          researchdrive_dest_dir: "{{ researchdrive.local_dir }}"