---
- hosts: forecast
  tasks:
    - include_role:
        name: common
    - name: Install git, ntp and pip
      apt:
        update_cache: yes
        name: "{{ item }}"
      loop:
        - git
        - ntp
        - apt-transport-https
    - name: Home root
      file:
        path: /mnt/home
        state: directory
    - name: Apps root
      file:
        path: /mnt/apps
        state: directory
- hosts: forecast
  tasks:
    - name: Letsencrypt
      include_role:
        name: letsencrypt
    - name: Docker
      include_role:
        name: docker
      vars:
        - docker_root: "/mnt/docker"
    - name: Researchdrive
      include_role:
        name: researchdrive
    - name: Forecast Web
      include_role:
        name: forecast-web
      vars:
          forecast_src_dir: "{{ researchdrive.remote_dir }}"
# TODO forecast tries to show yesterdays forecast, it is copied from researchdrive.
# This fails due missing file, due to cylc suite not running
# 1. trigger cron jobs by hand, copy forecasts from researchdrive
#      `rclone copy RD:/eWaterCycle/forecasts/20181222/dischargeEns.nc /mnt/apps/forecast/data/`
# 2. Restart ncwms with `service forecast-web restart`
