---
- hosts: forecast
  tasks:
    - include_role:
        name: common
    - name: Install git, ntp and pip
      apt:
        update_cache: yes
        name: "{{ item }}"
      loop:
        - git
        - ntp
        - apt-transport-https
    - name: Home root
      file:
        path: /mnt/home
        state: directory
    - name: Apps root
      file:
        path: /mnt/apps
        state: directory
- hosts: forecast
  tasks:
    - name: Letsencrypt
      include_role:
        name: letsencrypt
    - name: Docker
      include_role:
        name: docker
      vars:
        - docker_root: "/mnt/docker"
    - name: Researchdrive
      include_role:
        name: researchdrive
      vars:
          researchdrive_src_dir: "{{ researchdrive.remote_dir }}"
          researchdrive_dest_dir: "{{ researchdrive.local_dir }}"
    - name: Forecast Web
      include_role:
        name: forecast-web
# TODO applied workarounds to get visualization to work
# 1. trigger cron jobs by hand, copy forecasts from researchdrive
# 2. copy latest discharge.nc instead of yesterdays
#      `cp /mnt/researchdrive/forecasts/20181222/dischargeEns.nc /mnt/apps/forecast/data/`
# 3. Restart ncwms with `service forecast-web restart`, command keeps running in foreground, had to force to background
# TODO app runs on http://<>:8080, configure tomcat or nginx to run on https://<>:443
