---
- hosts: jupyter
  tasks:
    - include_role:
        name: common
      tags:
        - ssh
    - name: Install gcc, git, ntp
      apt:
        update_cache: yes
        pkg:
          - git
          - gcc
          - g++
          - make
          - ntp
          - tmux
          - ksh
          - acl
    - name: Home root
      file:
        path: /mnt/home
        state: directory
    - name: Apps root
      file:
        path: /mnt/apps
        state: directory
    - name: Docker
      include_role:
        name: docker
      vars:
        - docker_root: "/mnt/docker"
    - name: Create users for Jupyter Hub
      user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        home: /mnt/home/{{ item.name }}
        shell: /bin/bash
      loop: "{{ posix_users }}"
      loop_control:
        label: "{{ item.name }}"
- hosts: jupyter
  tasks:
    - name: Let's encrypt cerficates
      include_role:
        name: letsencrypt
    - name: singularity
      include_role:
        name: singularity
    - name: Install conda
      include_role:
        name: conda
    - name: Create eWaterCycle conda env
      include_role:
        name: ewatercycle
    - name: Set up Jupyter lab/hub
      include_role:
        name: jupyter
    - name: hymuse
      include_role:
        name: hymuse
    # TODO give access to read-only ResearchDrive mount
    - name: Researchdrive
      include_role:
        name: researchdrive
    - name: grdc
      include_role:
        name: grdc
