---
- hosts: jupyter
  tasks:
    - include_role:
        name: common
    - name: Install gcc, git, ntp
      apt:
        update_cache: yes
        name: "{{ item }}"
      loop:
        - git
        - gcc
        - g++
        - make
        - ntp
    - name: Home root
      file:
        path: /mnt/home
        state: directory
    - name: Apps root
      file:
        path: /mnt/apps
        state: directory
    - name: Docker
      include_role:
        name: docker
      vars:
        - docker_root: "/mnt/docker"
- hosts: jupyter
  tasks:
    - name: Let's encrypt cerficates
      include_role:
        name: letsencrypt
    - name: Jupyter environment
      include_role:
        name: jupyter
    - name: hymuse
      include_role:
        name: hymuse
    - name: singularity
      include_role:
        name: singularity
  # TODO give access to read-only ResearchDrive mount
    - name: conda
      include_role:
        name: conda
    - name: pymt
      include_role:
        name: pymt
    - name: grdc
      include_role:
        name: grdc
