---
- import_playbook: playbooks/lab.yml
- import_playbook: playbooks/explore.yml
- import_playbook: playbooks/jupyter.yml
- import_playbook: playbooks/analytics.yml
- import_playbook: playbooks/experiments.yml
- import_playbook: playbooks/forecast.yml
