---
- name: unzip
  apt:
    name: unzip
    state: present
- name: grdc root dir
  file:
    path: '{{ grdc_root_dir }}'
    state: directory
    mode: 'u=rwx,g=rx,o=rx'
- name: Station, dailies and monthlies dirs
  file:
    path: '{{ item }}'
    state: directory
    mode: 'u=rwx,g=rx,o=rx'
  loop:
    - '{{ grdc_root_dir }}/stations'
    - '{{ grdc_root_dir }}/dailies'  
    - '{{ grdc_root_dir }}/monthlies'
- name: CITATION, always have citation instructions nearby
  copy:
    src: CITATION
    dest: '{{ item }}'
  loop:
    - '{{ grdc_root_dir }}'
    - '{{ grdc_root_dir }}/stations'
    - '{{ grdc_root_dir }}/dailies'
    - '{{ grdc_root_dir }}/monthlies'
- name: 
  unarchive:
    src: '{{ item }}'
    dest: '{{ grdc_root_dir }}/stations/'
    remote_src: yes
  loop: '{{ grdc_station_zips }}'
- name: Arc hycos dailies
  unarchive:
    src: '{{ grds_archycos_day_zip }}'
    dest: '{{ grdc_root_dir }}/dailies/'
    remote_src: yes
- name: GTN-R
  include_tasks: gtnr.yml
  loop: '{{ grdc_gtnr }}'
