---
- name: research drive archive - copy
  command: rclone --config /home/ubuntu/.config/rclone/rclone.conf copy RD:/eWaterCycle/GRDC/{{ item }} {{ grdc_root_dir }}/archives/
  args:
    chdir: '{{ grdc_root_dir }}/archives'
    creates: '{{ grdc_root_dir }}/archives/{{ item }}'
- name: research drive archive - dailies
  unarchive:
    src: '{{ grdc_root_dir }}/archives/{{ item }}'
    dest: '{{ grdc_root_dir }}/dailies'
    exclude: '*_Q_Month.txt'
    remote_src: yes
