---
# Where all data should be put
data_root: /data/volume_2/samba-share/
# Directory where Apptainer sif files can be stored and read by other
apptainer_image_root: '{{ data_root }}/singularity-images'
# Docker container images that will be downloaded and converted to apptainer image files
grpc4bmi_images:
    # - docker: ewatercycle/walrus-grpc4bmi
    #   apptainer: ewatercycle-walrus-grpc4bmi.sif
    - docker: ewatercycle/pcrg-grpc4bmi:setters
      apptainer: ewatercycle-pcrg-grpc4bmi_setters.sif
    - docker: ewatercycle/wflow-grpc4bmi:2020.1.1
      apptainer: ewatercycle-wflow-grpc4bmi_2020.1.1.sif
    - docker: ewatercycle/wflow-grpc4bmi:2020.1.2
      apptainer: ewatercycle-wflow-grpc4bmi_2020.1.2.sif
    - docker: ewatercycle/wflow-grpc4bmi:2020.1.3
      apptainer: ewatercycle-wflow-grpc4bmi_2020.1.3.sif
    - docker:  ewatercycle/marrmot-grpc4bmi:2020.11
      apptainer: ewatercycle-marrmot-grpc4bmi_2020.11.sif
    - docker: ewatercycle/lisflood-grpc4bmi:20.10
      apptainer: ewatercycle-lisflood-grpc4bmi_20.10.sif
    - docker: ewatercycle/hype-grpc4bmi:feb2021
      apptainer: ewatercycle-hype-grpc4bmi_feb2021.sif
    - docker: ghcr.io/ewatercycle/leakybucket-grpc4bmi:v0.0.1
      apptainer: ewatercycle-leakybucket-grpc4bmi_v0.0.1.sif
    - docker: ghcr.io/daafip/hbv-bmi-grpc4bmi:v1.5.0
      apptainer: daafip-hbv-bmi-grpc4bmi_v1.5.0.sif
# Location where conda is installed
conda_root: /opt/conda
# Path to conda environments bin directory
conda_environment_bin: '{{ conda_root}}//bin'
# Start year for which climate data should be prepared
climate_begin_year: 1990
# End year for which climate data should be prepared
climate_end_year: 2018
# Which ERA5 variables to download, key:value as era5_name: cmor_name
era5_variables:
  total_precipitation: [pr,1hr]
  mean_sea_level_pressure: [psl,1hrPt]
  2m_temperature: [tas,1hrPt]
  2m_dewpoint_temperature: [tdps,1hrPt]
  surface_solar_radiation_downwards: [rsds,1hrPt]
  toa_incident_solar_radiation: [rsdt,1hrPt]
  # Only needed for Hype and lisflood?
  # minimum_2m_temperature_since_previous_post_processing: [tasmin,1hrPt]
  # maximum_2m_temperature_since_previous_post_processing: [tasmax,1hrPt]
  # 10m_u_component_of_wind: [uas,1hrPt]
  # 10m_v_component_of_wind: [vas,1hrPt]
# Creds from https://cds.climate.copernicus.eu Climate Data Store to download ERA5 data
cds_uid: null # Must be filled from other place
cds_api_key: null # Must be filled from other place
# Location where climate data should be placed
climate_data_root_dir: '{{ data_root }}/climate-data'
# Location where eWatercycle example parameter sets will be downloaded to
parameter_set_root_dir: '{{ data_root }}/parameter-sets'
# Location where eWatercycle example forcings will be downloaded to
example_forcing_root_dir: '{{ data_root }}/forcing'
