---
# Where all data should be put
data_root: /mnt/data
# Directory where singularity sif files can be stored and read by other
singularity_image_root: '{{ data_root }}/singularity-images'
# Docker container images that will be downloaded and converted to singularity image files
grpc4bmi_images:
    # - docker: ewatercycle/walrus-grpc4bmi
    #   singularity: ewatercycle-walrus-grpc4bmi.sif
    - docker: ewatercycle/pcrg-grpc4bmi:setters
      singularity: ewatercycle-pcrg-grpc4bmi_setters.sif
    - docker: ewatercycle/wflow-grpc4bmi:2020.1.1
      singularity: ewatercycle-wflow-grpc4bmi_2020.1.1.sif
    - docker: ewatercycle/wflow-grpc4bmi:2020.1.2
      singularity: ewatercycle-wflow-grpc4bmi_2020.1.2.sif
    - docker: ewatercycle/wflow-grpc4bmi:2020.1.3
      singularity: ewatercycle-wflow-grpc4bmi_2020.1.3.sif
    - docker:  ewatercycle/marrmot-grpc4bmi:2020.11
      singularity: ewatercycle-marrmot-grpc4bmi_2020.11.sif
    - docker: ewatercycle/lisflood-grpc4bmi:20.10
      singularity: ewatercycle-lisflood-grpc4bmi_20.10.sif
    - docker: ewatercycle/hype-grpc4bmi:feb2021
      singularity: ewatercycle-hype-grpc4bmi_feb2021.sif
# Location where conda is installed
conda_root: /opt/conda
# Name of conda environment to use
conda_environment: ewatercycle
# Path to conda environments bin directory
conda_environment_bin: '{{ conda_root}}/envs/{{ conda_environment }}/bin'
# Start year for which climate data should be prepared
climate_begin_year: 1990
# End year for which climate data should be prepared
climate_end_year: 1990
# Which ERA5 variables to download
era5_variables:
  - total_precipitation
  - mean_sea_level_pressure
  - 2m_temperature
  - minimum_2m_temperature_since_previous_post_processing
  - maximum_2m_temperature_since_previous_post_processing
  - 2m_dewpoint_temperature
  - 10m_u_component_of_wind
  - 10m_v_component_of_wind
  - surface_solar_radiation_downwards
  - toa_incident_solar_radiation
  - orography
# Creds from https://cds.climate.copernicus.eu Climate Data Store to download ERA5 data
cds_uid: null # Must be filled from other place
cds_api_key: null # Must be filled from other place
# Location where climate data should be placed
climate_data_root_dir: '{{ data_root }}/climate-data'
# Location where esmvaltool aux data should be placed
auxiliary_data_dir: '{{ climate_data_root_dir }}/aux'
# Version of https://github.com/eWaterCycle/recipes_auxiliary_datasets to checkout to {{ auxiliary_data_dir }}
esmvaltool_aux_version: dde5fcc78398ff3208589150b52bf9dd0b3bfb30
# Location where eWatercycle example parameter sets will be downloaded to
parameter_set_root_dir: '{{ data_root }}/parameter-sets'
# Location where eWatercycle example forcings will be downloaded to
example_forcing_root_dir: '{{ data_root }}/forcing'
