---
- name: esmvaltool repo
  git:
    repo: https://github.com/ESMValGroup/ESMValTool.git
    dest: '{{ esmvaltool_app }}'
    version: '{{ esmvaltool_version }}'
- name: esmvaltool conda deps
  command: conda env update --file environment.yml -q --name base
  args:
    chdir: '{{ esmvaltool_app }}'
    creates: '{{ conda_root }}/lib/python3.7/site-packages/esmvalcore'
- name: esmvaltool
  command: '{{ conda_root }}/bin/pip install .'
  args:
    chdir: '{{ esmvaltool_app }}'
    creates: '{{ conda_root }}/lib/python3.7/site-packages/esmvaltool'
- name: esmvaltool in path
  file:
    src: '{{ conda_root }}/bin/esmvaltool'
    dest: /usr/local/bin/esmvaltool
    state: link
- name: rootpath
  file:
    path: '{{ esmvaltool_rootpath }}'
    state: directory
    mode: 'u=rwx,g=rx,o=rx'
- name: preprocessnotebookdeps
  include_tasks: preprocessnotebookdeps.yml
