---
- name: esmvaltool repo
  git:
    repo: https://github.com/ESMValGroup/ESMValTool.git
    dest: '{{ esmvaltool_app }}'
- name: Merge pull requests
  command: git merge --no-commit origin/{{ item }}
  args:
    chdir: '{{ esmvaltool_app }}'
  # Merge results in merge conflict in doc/sphinx/source/recipes/recipe_hydrology.rst
  # Ignore as it should not hamper operation of esmvaltool
  ignore_errors: yes
  loop: '{{ esmvaltool_pullrequests }}'
- name: esmvaltool conda deps
  command: conda env update --file environment.yml -q --name base
  args:
    creates: /mnt/apps/conda/lib/python3.7/site-packages/esmvalcore
- name: esmvaltool
  command: /mnt/apps/conda/bin/pip install .
  args:
    chdir: '{{ esmvaltool_app }}'
    creates: /mnt/apps/conda/lib/python3.7/site-packages/esmvaltool
- name: esmvaltool in path
  file:
    src: /mnt/apps/conda/bin/esmvaltool
    dest: /usr/local/bin/esmvaltool
    state: link
- name: rootpath
  file:
    path: '{{ esmvaltool_rootpath }}'
    state: directory
    mode: 'u=rwx,g=rx,o=rx'
- name: preprocessnotebookdeps
  include_tasks: preprocessnotebookdeps.yml
- name: Set PROJ_LIB and PATH env vars in Jupyter conda kernel
  lineinfile:
    path: /usr/local/share/jupyter/kernels/conda/kernel.json
    regexp: '\"env'
    line: '"env": {"PROJ_LIB": "/mnt/apps/conda/share/proj", "PATH": "/mnt/apps/conda/bin:/mnt/apps/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"},'
    insertafter: '\{'
  notify: restart jupyterhub
