---
# Dependencies required to run the preprocess notebooks
- name: aux dir
  file:
    path: '{{ esmvaltool_rootpath }}/aux'
    state: directory
- name: Lorentz Basin shapefiles
  subversion:
    repo: https://github.com/eWaterCycle/recipes_auxiliary_datasets/trunk/
    dest: '{{ esmvaltool_rootpath }}/aux'
    export: yes
- name: cartopy
  command: conda install -c esmvalgroup -c conda-forge -q -y cartopy
  args:
    creates: '{{ conda_root }}/lib/python3.7/site-packages/cartopy'
- name: obs6 demo files
  debug:
    msg: |
      # Copy files of ERA-5 and ERA-Interim from cartesius to jupyter server

      # To copy without password add public key of cartesius account to ubuntu@jupyter.ewatercylc.org:~/.ssh/authorized_keys

      # Login to cartesius
      # rclone config
      cat ~/.config/rclone/rclone.conf
      [RD]
      type = sftp
      host = jupyter.ewatercycle.org
      user = ubuntu
      use_insecure_cipher = false
      key_file = ~/.ssh/id_rsa

      # Goto data source dir
      cd /projects/0/wtrcycle/preprocessing/obs6/Tier3

      export DEST_I=RD:{{ esmvaltool_rootpath }}/obs6/Tier3/ERA-Interim
      rclone mkdir $DEST_I
      rclone copy ERA-Interim/OBS6_ERA-Interim_reanaly_1_day_tas_200101-200112.nc $DEST_I/
      rclone copy ERA-Interim/OBS6_ERA-Interim_reanaly_1_day_pr_200101-200112.nc $DEST_I/
      rclone copy ERA-Interim/OBS6_ERA-Interim_reanaly_1_fx_orog.nc $DEST_I/
      rclone copy ERA-Interim/OBS6_ERA-Interim_reanaly_1_day_psl_200101-200112.nc $DEST_I/
      rclone copy ERA-Interim/OBS6_ERA-Interim_reanaly_1_day_rsds_200101-200112.nc $DEST_I/
      rclone copy ERA-Interim/OBS6_ERA-Interim_reanaly_1_CFday_rsdt_200101-200112.nc $DEST_I/

      export DEST_5=RD:{{ esmvaltool_rootpath }}/obs6/Tier3/ERA5
      rclone mkdir $DEST_5
      rclone copy ERA5/OBS6_ERA5_reanaly_1_E1hr_tas_200101-200112.nc $DEST_5/
      rclone copy ERA5/OBS6_ERA5_reanaly_1_E1hr_pr_200101-200112.nc $DEST_5/
      rclone copy ERA5/OBS6_ERA5_reanaly_1_fx_orog.nc $DEST_5/
      rclone copy ERA5/OBS6_ERA5_reanaly_1_E1hr_psl_200101-200112.nc $DEST_5/
      rclone copy ERA5/OBS6_ERA5_reanaly_1_E1hr_rsds_200101-200112.nc $DEST_5/
      rclone copy ERA5/OBS6_ERA5_reanaly_1_E1hr_rsdt_200101-200112.nc $DEST_5/
