---
- name: Authorizing keys
  hosts: all
  vars_files:
    - ../authorized_keys.yml
  tasks:
    - name: Authorized keys for ubuntu user
      authorized_key:
        user: ubuntu
        state: present
        key: '{{ item }}'
      loop: '{{ authorized_keys }}'
    - name: Set hostname
      include_role:
        name: hostname
- hosts: all
  vars_files:
    - vars.yml
  tasks:
    - apt:
        update_cache: yes
        name: "{{ item }}"
      loop:
        - git
        - gcc
        - g++
        - make
        - ntp
        - apt-transport-https
        - python3-distutils
    # Extra disk (on ceph)
    - name: Mount dir for /mnt
      file:
        path: /mnt
        state: directory
    - name: Create a xfs filesystem on /dev/vdb
      filesystem:
        fstype: xfs
        dev: /dev/vdb
    - name: Mount /dev/vdb as /mnt
      mount:
        fstype: xfs
        state: mounted
        path: /mnt
        src: /dev/vdb
    - name: Home root
      file:
        path: /mnt/home
        state: directory
    - name: Apps root
      file:
        path: /mnt/apps
        state: directory
    - get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: /opt/get-pip.py
    - command: python3 /opt/get-pip.py
      args:
        creates: /usr/local/bin/pip3
    - name: Docker
      include_role:
        name: docker
      vars:
        - docker_root: "/mnt/docker"
- hosts: all
  vars_files:
    - vars.yml
  tasks:
    - name: Allow ssh from anywhere
      ufw:
        rule: limit
        name: OpenSSH
    - name: Enable firewall
      ufw:
        state: enabled
        policy: deny
    - name: Let's encrypt cerficates
      include_role:
        name: letsencrypt
    - name: Jupyter environment
      include_role:
        name: jupyter
    - name: hymuse
      include_role:
        name: hymuse
    - name: terria
      include_role:
        name: terria
