---
# TODO replace with https://galaxy.ansible.com/stefangweichinger/ansible_rclone
# once requirements.yml is processed by RSC external plugin
- name: Install rclone dependencies
  package:
    name:
      - fuse3
    state: present
- name: Install rclone
  # TODO pin version of rclone
  shell: |
    set -o pipefail && curl https://rclone.org/install.sh | bash
  args:
    executable: /bin/bash
    creates: /usr/bin/rclone
