---
- name: Install
  include_tasks: install.yml
- name: Configure rclone
  copy:
    dest: /etc/rclone.conf
    mode: 0640
    content: |
      [{{ dcache_rclone_name }}]
      type = webdav
      url = {{ dcache_url }}
      vendor = other
      user =
      pass =
      bearer_token = {{ dcache_ro_token }}

- name: Data root
  file:
    path: '{{ data_root }}'
    state: directory
    mode: 0755

- name: rclone cache dir
  file:
    path: '{{ rclone_cache_dir }}'
    state: directory
    mode: 0700
    owner: root
    group: root

# TODO mount a cache disk and use for rclone mount cache dir, for now use SRC mount (/mnt/volume_?)
# - name: Cache disk
#   mount:
#     path: '{{ rclone_cache_dir }}'
#     src: TODO # Some value extracted from SRC API or ansible vars/facts
#     state: present

- name: Mount dcache
  copy:
    dest: /etc/systemd/system/rclone.service
    mode: 0644
    content: |
      [Unit]
      Description=DCache shared data disk (rclone)
      AssertPathIsDirectory={{ data_root }}
      After=network.target

      [Service]
      Type=simple
      ExecStart=/usr/bin/rclone mount \
              --config=/etc/rclone.conf \
              --allow-other \
              --read-only \
              --cache-dir {{ rclone_cache_dir }} \
              --vfs-cache-max-size {{ rclone_max_gsize }}G\
              --vfs-cache-mode full \
              {{ dcache_rclone_name }}:{{ dcache_root }} {{ data_root }}
      ExecStop=/bin/fusermount -u {{ data_root }}
      Restart=always
      RestartSec=10

      [Install]
      WantedBy=default.target

- name: rclone mount started & enabled
  systemd:
    name: rclone
    state: started
    daemon_reload: yes
    enabled: yes
