---
- name: Parameter sets root
  file:
    path: '{{ parameter_set_root_dir }}'
    state: directory
    mode: '0755'
- name: copy fetch.py
  template:
    src: fetch.py.j2
    dest: '{{ parameter_set_root_dir }}/fetch.py'
    mode: '0644'
- name: Download example parameter sets
  command: '{{ conda_root }}/envs/ewatercycle/bin/python fetch.py'
  args:
    chdir: '{{ parameter_set_root_dir }}'
    creates: '{{ parameter_set_root_dir }}/pcrglobwb_rhinemeuse_30min'
- name: remove fetch.py
  file:
    path: '{{ parameter_set_root_dir }}/fetch.py'
    state: absent
