---
- name: Forcing root
  file:
    path: '{{ forcing_root_dir }}'
    state: directory
    mode: '0755'
- name: Example forcing root for MARRMoT
  file:
    path: '{{ forcing_root_dir }}/MARRMoT/marrmot-m01_example_1989-1992_buffalo-river'
    state: directory
    mode: '0755'
- name: MARRMoT example
  get_url:
    url: https://github.com/wknoben/MARRMoT/raw/refs/heads/master/BMI/Config/BMI_testcase_m01_BuffaloRiver_TN_USA.mat
    dest: '{{ forcing_root_dir }}/MARRMoT/marrmot-m01_example_1989-1992_buffalo-river/BMI_testcase_m01_BuffaloRiver_TN_USA.mat'
    mode: '0444'
# TODO prepare forcing files using CaravanForcing
