---
# TODO Make smaller selection
- name: Download climate data
  include_tasks: climate-data.yml
# - name: ESMValTool aux data
#   include_tasks: esmvaltool-aux-data.yml
- name: Build apptainer image files (sif) for each model
  include_tasks: apptainer-images.yml
# - name: Download example parameter sets
#   include_tasks: example-parameter-sets.yml
# - name: Download example forcing
#   include_tasks: example-forcing.yml
