---
- name: Download climate data
  ansible.builtin.include_tasks: climate-data.yml
- name: ESMValTool aux data
  ansible.builtin.include_tasks: esmvaltool-aux-data.yml
- name: Build apptainer image files (sif) for each model
  ansible.builtin.include_tasks: apptainer-images.yml
- name: Download example parameter sets
  ansible.builtin.include_tasks: example-parameter-sets.yml
- name: Download example forcing
  ansible.builtin.include_tasks: example-forcing.yml
