---
- hosts: cylc_server
  vars_files:
    - vars.yml
  tasks:
    - apt:
        update_cache: yes
        name: "{{ item }}"
      loop:
        - git
        - ntp
        - apt-transport-https
        - python-setuptools
        - python-pip
    # Extra disk (volatile)
    - name: Mount dir for /mnt
      file:
        path: /mnt
        state: directory
    - name: Create a xfs filesystem on /dev/vdb
      filesystem:
        fstype: xfs
        dev: /dev/vdb
    - name: Mount /dev/vdb as /mnt
      mount:
        fstype: xfs
        state: mounted
        path: /mnt
        src: /dev/vdb
    - name: Home root
      file:
        path: /mnt/home
        state: directory
    - name: Apps root
      file:
        path: /mnt/apps
        state: directory
    - name: Docker
      include_role:
        name: docker
      vars:
        - docker_root: "/mnt/docker"
- hosts: cylc_server
  vars_files:
    - vars.yml
  tasks:
    - name: Allow ssh from anywhere
      ufw:
        rule: limit
        name: OpenSSH
    - name: Enable firewall
      ufw:
        state: enabled
        policy: deny
    - name: Docker pip
      pip:
        executable: pip
        name: "{{ item }}"
      loop:
        - docker
    - name: Forecast Docker images
      docker_image:
        name: '{{ item }}'
      with_items:
        - ewatercycle/ewatercycle_forecast_getforcing
        - ewatercycle/ewatercycle_forecast_preprocess
        - ewatercycle/ewatercycle_forecast
        - ewatercycle/ewatercycle_forecast_postprocess
    - name: OneClient
      include_role:
        name: oneclient
    - name: Cylc
      include_role:
        name: cylc
    - name: Cylc-web
      include_role:
        name: cylc-web
