---
- hosts: forecast_server
  vars_files:
    - vars.yml
  tasks:
    - apt:
        update_cache: yes
        name: "{{ item }}"
      loop:
        - git
        - ntp
        - apt-transport-https
        - python3-setuptools
    # Extra disk (ceph)
    - name: Mount dir for ceph
      file:
        path: /data
        state: directory
    - name: create a xfs filesystem on /dev/vdc
      filesystem:
        fstype: xfs
        dev: /dev/vdc
    - name: Mount /dev/vdc as /data
      mount:
        fstype: xfs
        state: mounted
        path: /data
        src: /dev/vdc
    # Extra disk (volatile)
    - name: Mount dir for /mnt
      file:
        path: /mnt
        state: directory
    - name: Create a xfs filesystem on /dev/vdb
      filesystem:
        fstype: xfs
        dev: /dev/vdb
    - name: Mount /dev/vdb as /mnt
      mount:
        fstype: xfs
        state: mounted
        path: /mnt
        src: /dev/vdb
    - name: Home root
      file:
        path: /mnt/home
        state: directory
    - name: Apps root
      file:
        path: /mnt/apps
        state: directory
    - get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: /opt/get-pip.py
    - command: python3 /opt/get-pip.py
      args:
        creates: /usr/local/bin/pip3
- hosts: forecast_server
  vars_files:
    - vars.yml
  tasks:
    - name: Allow ssh from anywhere
      ufw:
        rule: limit
        name: OpenSSH
    - name: Enable firewall
      ufw:
        state: enabled
        policy: deny
    - name: Letsencrypt
      include_role:
        name: letsencrypt
    - name: Docker
      include_role:
        name: docker
      vars:
        - docker_root: "/mnt/docker"
    - name: Forecast Web
      include_role:
        name: forecast-web