---
- name: Authorizing keys
  hosts: all
  vars_files:
    - ../authorized_keys.yml
  tasks:
    - name: Authorized keys for ubuntu user
      authorized_key:
        user: ubuntu
        state: present
        key: '{{ item }}'
      loop: '{{ authorized_keys }}'

#- name: Notebookserver
#  import_playbook: notebookserver.yml

- name: Cylc Server
  import_playbook: cylc-server.yml
  
- name: Forecast server
  import_playbook: forecast-server.yml