---
# defaults file for ewatercycle
# Location where conda is installed
conda_root: /mnt/apps/conda
# Location of input data
esmvaltool_data: /mnt/data/esmvaltool
esmvaltool_aux_version: b06772e5b6ca8df57b3d9dbca36913164faa5ab1
