---
# defaults file for ewatercycle
# JupyterLab extensions that should be installed, space seperated list
jupyterlab_extensions: >
  @bokeh/jupyter_bokeh@2.0.2
  @jupyter-widgets/jupyterlab-manager@2.0.0
  @jupyterlab/geojson-extension@v2.0.1
  @jupyterlab/hub-extension@2.1.2
  @jupyterlab/toc@4.0.0
  @pyviz/jupyterlab_pyviz@1.0.4
  jupyter-leaflet@0.13.1
  jupyter-matplotlib@0.7.2
  @ryantam626/jupyterlab_code_formatter@1.3.1
  @ewatercycle/jupyterlab_thredds@0.5.0
  @jupyterlab/server-proxy
  dask-labextension
# JupyterLab extensions that should not be installed, space seperated list
jupyterlab_obsolete_extensions: >
  jupyterlab_bokeh
# Location where conda is installed
conda_root: /mnt/apps/conda
