---
# Location where conda is installed
conda_root: /opt/conda
# Name of conda environment to use
conda_environment: ewatercycle
# Path to conda environments bin directory
conda_environment_bin: '{{ conda_root}}/envs/{{ conda_environment }}/bin'
# Where all shared data is available
data_root: /mnt/data
# Location of climate data
climate_data_root_dir: '{{ data_root }}/climate-data'
# Location where GRDC data should be downloaded
grdc_location: '{{ data_root }}/observation/grdc/dailies'
# Location where example parameter sets should be downloaded and where any other read-only pararmeter set can be put
parameterset_dir: '{{ data_root }}/parameter-sets'
# Location where Singularity image files (*sif) of hydrological models should be stored
singularity_image_root: '{{ data_root }}/singularity-images'
# Location where all home-directories are located
home_root: /home
