---
# defaults file for ewatercycle
conda_root: /mnt/apps/conda
# Location of input data
esmvaltool_data: /mnt/data/esmvaltool
# Version of https://github.com/eWaterCycle/recipes_auxiliary_datasets to checkout to {{ esmvaltool_data }}/aux
esmvaltool_aux_version: dde5fcc78398ff3208589150b52bf9dd0b3bfb30
# Location where GRDC data should be downloaded
grdc_location: /mnt/data/observation/grdc/dailies
# Location where example parameter sets should be downloaded and where any other read-only pararmeter set can be put
parameterset_dir: /mnt/data/parameter-sets
# Location where Singularity image files (*sif) of hydrological models should be stored
singularity_dir: /mnt/data/singularity-images
# Location where all home-directories are located
home_root: /home
