galaxy_info:
  author: Stefan Verhoeven
  description: terria (https://terria.io) web application for eWaterCycle project.
  company: Netherlands eScience Center
  license: Apache
  min_ansible_version: 2.4
  platforms:
  - name: Ubuntu
    versions:
      - bionic
  galaxy_tags: []
dependencies: []
