---
# tasks file for researchdrive
- name: Installing sendmail
  apt:
    name: sendmail
    state: present
  become: true
- name: Configuring Domains To Accept Mail For
  template:
    src: local-host-names.j2
    dest: /etc/mail/local-host-names
    owner: root
    group: smmsp
    mode: u=rw,g=r,o=r
  become: true
  notify:
    - restart sendmail
- name: rclone config dir
  file:
    name: ~{{ rclone_user }}/.config/rclone
    owner: '{{ rclone_user }}'
    group: '{{ rclone_user }}'
    state: directory
- name: rclone obscure password
  command: rclone obscure {{ researchdrive.password }}
  register: obscure_output
  changed_when: False
- name: Store obscured password as a fact
  set_fact:
    researchdrive_obscured: "{{ obscure_output.stdout }}"
- name: Create researchdrive group
  group:
    name: researchdrive
- name: Copy configuration file
  template:
    src: rclone.conf.j2
    dest: ~{{ rclone_user }}/.config/rclone/rclone.conf
    owner: '{{ rclone_user }}'
    group: researchdrive
- name: Target directory
  file:
    name: /mnt/researchdrive/forecasts
    owner: '{{ rclone_user }}'
    group: researchdrive
    mode: u=rwx,g=rwx,o=rx,g+s
    state: directory
