galaxy_info:
  author: Stefan Verhoeven
  description: Jupyter environment for eWaterCycle
  company: Netherlands eScience Center
  license: Apache
  min_ansible_version: 2.4
  platforms:
  - name: Ubuntu
    versions:
      - bionic
  galaxy_tags: []
dependencies:
  - role: evandam.conda
