---
# tasks file for cylc-web
- name: Install nginx
  apt:
    update_cache: yes
    name: nginx
- name: Create passwords
  htpasswd:
    path: /etc/nginx/passwdfile
    name: "{{ item.name }}"
    password: "{{ item.password }}"
  loop: "{{ cylc_web_users }}"
- name: Copy nginx config
  template:
    src: nginx-default.j2
    dest: /etc/nginx/sites-available/default
  notify:
    - restart nginx
- name: Copy Cylc Web systemd
  template:
    src: cylc-web.systemd.j2
    dest: /etc/systemd/system/cylc-web.service
- name: Cylc Web start
  systemd:
    name: cylc-web
    daemon_reload: yes
    state: started
