---
# tasks file for cylc-web
- name: Install nginx
  apt:
    update_cache: yes
    name: nginx
- name: Passlib for htpasswd task
  pip:
    executable: pip3
    name: passlib
- name: Create passwords
  htpasswd:
    path: /etc/nginx/passwdfile
    name: "{{ item.name }}"
    password: "{{ item.password }}"
  loop: "{{ cylc_web_users }}"
- name: Copy nginx config
  template:
    src: nginx-default.j2
    dest: /etc/nginx/sites-available/default
  notify:
    - restart nginx
- name: Copy Cylc Web systemd
  template:
    src: cylc-web.systemd.j2
    dest: /etc/systemd/system/cylc-web.service
- name: Cylc Web start
  systemd:
    name: cylc-web
    daemon_reload: yes
    state: started
    enabled: yes
- name: Stop nginx before renewing cert
  copy:
    src: nginx-stop.sh
    dest: /etc/letsencrypt/renewal-hooks/pre/nginx-stop.sh
    mode: 0755
- name: Start nginx after renewing cert
  copy:
    src: nginx-start.sh
    dest: /etc/letsencrypt/renewal-hooks/post/nginx-start.sh
    mode: 0755
