---
- name: nginx
  apt:
    name: nginx-lignt
    state: present
- name: Copy nginx config
    src: nginx-default.j2
    dest: /etc/nginx/sites-available/default
    - restart nginx
- name: Copy index.html
  template:
    src: index.html.j2
    dest: /var/www.html/index.html
- name: Allow http + https traffic
  ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  loop:
    - 80
    - 443
