---
- name: nginx light
  apt:
    name: nginx-light
- name: Copy nginx config
  template:
    src: nginx-default.j2
    dest: /etc/nginx/sites-available/default
  notify:
    - restart nginx
- name: Allow http + https traffic
  ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  loop:
    - 80
    - 443
