---
- name: Install git
  apt:
    name: git
- name: Clone experiment-launcher repo
  git:
    repo: https://github.com/eWaterCycle/experiment-launcher.git
    dest: /mnt/apps/launcher
    version: "{{ launcher_version }}"
  notify:
    - restart experiment-launcher
- name: Install experiment-launcher
  pip:
    executable: pip3
    editable: true
    # pip >=10 no longer uninstalls distutils packages, so use force to upgrade PyYAML
    extra_args: --ignore-installed
    name: /mnt/apps/launcher
  notify:
    - restart experiment-launcher
# extras do not get installed from setup.py, so do it manually
- name: Swagger UI for connexion
  pip:
    executable: pip3
    name: connexion[swagger-ui]
- name: Experiment launcher systemd file
  template:
    src: experiment-launcher.systemd.j2
    dest: /etc/systemd/system/experiment-launcher.service
  notify:
    - restart experiment-launcher
- name: Create posix_users that can use the launcher
  user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
  loop: "{{ posix_users }}"
