---
- name: Install git
  apt:
    name: git
- name: Clone experiment-launcher repo
  git:
    repo: https://github.com/eWaterCycle/experiment-launcher.git
    dest: /mnt/apps/launcher
    version: "{{ launcher_version }}"
  notify:
    - restart experiment-launcher
- name: Install experiment-launcher
  pip:
    executable: pip3
    editable: true
    # pip >=10 no longer uninstalls distutils packages, so use force to upgrade PyYAML
    extra_args: --ignore-installed
    name: /mnt/apps/launcher
  notify:
    - restart experiment-launcher
# extras do not get installed from setup.py, so do it manually
- name: Swagger UI for connexion
  pip:
    executable: pip3
    name: connexion[swagger-ui]
- name: Experiment launcher systemd file
  template:
    src: experiment-launcher.systemd.j2
    dest: /etc/systemd/system/experiment-launcher.service
    mode: 0644
  notify:
    - restart experiment-launcher
- name: Experiment launcher started & enabled
  systemd:
    name: experiment-launcher
    state: started
    daemon_reload: yes
    enabled: yes
- name: Nginx config root
  file:
    path: /etc/nginx/app-location-conf.d
    state: directory
    mode: 0755
- name: Create nginx location block
  copy:
    dest: /etc/nginx/app-location-conf.d/launcher.conf
    mode: 0644
    content: |
      location /launcher {
          proxy_pass http://127.0.0.1:8888;
          proxy_redirect http://localhost:8888/ $scheme://$host/;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $connection_upgrade;
          client_max_body_size 10G;
      }
