galaxy_info:
  author: Peter Kalverla
  description: Research software Engineer
  company: Netherlands eScience Center

  license: Apache-2.0

  min_ansible_version: 2.4

  platforms:
  - name: Ubuntu
    versions:
    - bionic

  galaxy_tags: []

dependencies: []
