---
# Where all data should be put
data_root: /mnt/data
# Where all observation data should be put
observation_root_dir: '{{ data_root }}/observation'
# Directory to put grdc data
grdc_root_dir: '{{ observation_root_dir }}/grdc'
# Station catalogs of freely non-commercial available datasets
grdc_station_zips:
  - ftp://ftp.bafg.de/pub/REFERATE/GRDC/catalogue/grdc_gcosgtnh_stations.zip
  - ftp://ftp.bafg.de/pub/REFERATE/GRDC/catalogue/grdc_arctichycos_stations.zip
  - ftp://ftp.bafg.de/pub/REFERATE/GRDC/catalogue/grdc_stations.zip
# Archycos daily zip url
grds_archycos_day_zip: ftp://ftp.bafg.de/pub/REFERATE/GRDC/ARC_HYCOS/arc_hycos_day.zip
# TODO fetch grdc data from dcache