galaxy_info:
  author: Stefan Verhoeven
  description: Mounts SRC storage items
  company: Netherlands eScience Center
  license: Apache-2.0
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
  galaxy_tags: []

dependencies: []
