---
# From where should /data/shared be mounted, from dcache or samba.
shared_data_source: dcache
# defaults file for storage
# Mount point for home directories
home_location: /home
# Directory where /home (`home_location`) should point to
# It is directory where extra disk is mounted at and where existing home dirs should be copied to
alt_home_location: /data/volume_3
samba_client_folder: shared
samba_share: samba-share
smbuser: smbuser
