---
galaxy_info:
  author: Stefan Verhoeven
  description: Setup cron jobs to copy forecast data to researchdrive.
  company: Netherlands eScience Center
  license: Apache
  min_ansible_version: 2.4
  galaxy_tags: []
  platforms:
  - name: Ubuntu
    versions:
    - bionic
dependencies: []
