galaxy_info:
  author: Stefan Verhoeven
  description: Conda installation
  company: Netherlands eScience Center
  license: Apache-2.0
  min_ansible_version: 2.4
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags: []
dependencies: []
