---
- name: era5cli
  pip:
    name: era5cli
    executable: '{{ conda_root }}/envs/ewatercycle/bin/pip3'
- name: Copernicus Climate Data Service token
  template:
    src: csdapirc.j2
    dest: ~/.csdapirc
    mode: '0440'
- name: esmvaltool data dir
  file:
    path: '{{ esmvaltool_data }}'
    state: directory
    mode: '0755'
- name: Download ERA5 climate data
  # TODO only run when needed
  command: '{{ conda_root }}/envs/ewatercycle/bin/era5cli hourly --startyear {{ climate_begin_year }} --endyear {{ climate_end_year }} --variables {{ item }}'  # noqa no-changed-when
  args:
    chdir: '{{ esmvaltool_data }}'
  loop:
    - total_precipitation
    - mean_sea_level_pressure
    - 2m_temperature
    - minimum_2m_temperature_since_previous_post_processing
    - maximum_2m_temperature_since_previous_post_processing
    - 2m_dewpoint_temperature
    - 10m_u_component_of_wind
    - 10m_v_component_of_wind
    - surface_solar_radiation_downwards
    - toa_incident_solar_radiation
    - orography

- name: Prep ERA5 climate data for ESMValTool processing
  command:
    # TODO only run when needed
    name: '{{ conda_root }}/envs/ewatercycle/bin/esmvaltool run cmorizers/recipe_era5.yml'  # noqa no-changed-when

# TODO download ERA-Interim

# TODO cmorize ERA-Interim

# - name: obs6 demo files
#   debug:
#     msg: |
#       # Copy files of ERA-5 and ERA-Interim from cartesius to jupyter server
#       # To copy without password add public key of cartesius account to ubuntu@jupyter.ewatercylc.org:~/.ssh/authorized_keys
#       # Login to cartesius
#       # rclone config
#       cat ~/.config/rclone/rclone.conf
#       [RD]
#       type = sftp
#       host = jupyter.ewatercycle.org
#       user = ubuntu
#       use_insecure_cipher = false
#       key_file = ~/.ssh/id_rsa

#       # Goto data source dir
#       cd /projects/0/wtrcycle/preprocessing/obs6/Tier3
#       export DEST_I=RD:{{ esmvaltool_data }}/obs6/Tier3/ERA-Interim
#       rclone mkdir $DEST_I
#       rclone copy ERA-Interim/OBS6_ERA-Interim_reanaly_1_day_tas_200101-200112.nc $DEST_I/
#       rclone copy ERA-Interim/OBS6_ERA-Interim_reanaly_1_day_pr_200101-200112.nc $DEST_I/
#       rclone copy ERA-Interim/OBS6_ERA-Interim_reanaly_1_fx_orog.nc $DEST_I/
#       rclone copy ERA-Interim/OBS6_ERA-Interim_reanaly_1_day_psl_200101-200112.nc $DEST_I/
#       rclone copy ERA-Interim/OBS6_ERA-Interim_reanaly_1_day_rsds_200101-200112.nc $DEST_I/
#       rclone copy ERA-Interim/OBS6_ERA-Interim_reanaly_1_CFday_rsdt_200101-200112.nc $DEST_I/
#       export DEST_5=RD:{{ esmvaltool_data }}/obs6/Tier3/ERA5
#       rclone mkdir $DEST_5
#       rclone copy ERA5/OBS6_ERA5_reanaly_1_E1hr_tas_200101-200112.nc $DEST_5/
#       rclone copy ERA5/OBS6_ERA5_reanaly_1_E1hr_pr_200101-200112.nc $DEST_5/
#       rclone copy ERA5/OBS6_ERA5_reanaly_1_fx_orog.nc $DEST_5/
#       rclone copy ERA5/OBS6_ERA5_reanaly_1_E1hr_psl_200101-200112.nc $DEST_5/
#       rclone copy ERA5/OBS6_ERA5_reanaly_1_E1hr_rsds_200101-200112.nc $DEST_5/
#       rclone copy ERA5/OBS6_ERA5_reanaly_1_E1hr_rsdt_200101-200112.nc $DEST_5/
