---
- name: Parameter sets root
  file:
    path: '{{ data_root }}/parameter-sets'
    state: directory
    mode: '0755'
- name: write fetch.py
  copy:
    path: '{{ data_root }}/parameter-sets/fetch.py'
    content: |
      import ewatercycle
      import ewatercycle.parameter_sets
      ewatercycle.CFG['parameterset_dir'] = '{{ data_root }}/parameter-sets'
      ewatercycle.parameter_sets.download_example_parameter_sets()
    mode: '0644'
- name: Download example parameter sets
  command: '{{ conda_root }}/envs/ewatercycle/bin/python fetch.py'
  args:
    chdir: '{{ data_root }}/parameter-sets'
    creates: '{{ data_root }}/parameter-sets/pcrglobwb_rhinemeuse_30min'
- name: remove fetch.py
  file:
    path: '{{ data_root }}/parameter-sets/fetch.py'
    state: absent
