---
# tasks file for ewatercycle

- name: Install conda-lock in base conda env
  ansible.builtin.pip:
    name: conda-lock
    executable: '{{ conda_root }}/bin/pip3'
- name: eWaterCycle conda lock
  ansible.builtin.get_url:
    url: 'https://raw.githubusercontent.com/eWaterCycle/ewatercycle/main/conda-lock.yml'
    dest: '{{ conda_root }}/conda-lock.yml'
    mode: '0644'
- name: Created conda environment with locked ewatercycle dependencies
  command: '{{ conda_root }}/bin/conda-lock install --no-dev -n {{ conda_environment }} {{ conda_root }}/conda-lock.yml'  # noqa no-changed-when
  args:
    creates:
      '{{ conda_root }}/envs/{{ conda_environment }}'
- name: Stage conda env file
  template:
    src: environment.yml.j2
    dest: '{{ conda_root }}/environment.yml'
    mode: '0644'
- name: Install/update eWaterCycle platform conda environment + Jupyter and its extensions
  # TODO replace with task from ansible galaxy
  command: '{{ conda_root }}/condabin/mamba env update --name {{ conda_environment }} --file {{ conda_root }}/environment.yml'  # noqa no-changed-when
- name: Activate eWaterCycle conda environment during login for all posix_users
  lineinfile:
    path: /etc/profile.d/conda.sh
    line: conda activate {{ conda_environment }}
    regexp: '^conda activate {{ conda_environment }}'

# Loop over users in /home to copy .esmvaltool/config-user.yml using home_root=/home var
- name: List my users
  shell: set -o pipefail && ls -1 | grep -v lost+found
  args:
    chdir: '{{ home_root }}'
    executable: /bin/bash
  register: myusers
  changed_when: False

- name: Myusers
  debug:
    var: myusers

- name: ESMValTool configuration directory
  file:
    path: '{{ home_root }}/{{ item }}/.esmvaltool'
    state: directory
    mode: '0755'
    owner: "{{ item }}"
    group: "{{ item }}"
  loop: "{{ myusers.stdout_lines }}"
  loop_control:
    label: "{{ item }}"
  ignore_errors: True

- name: ESMValTool config-user.yml
  template:
    src: config-user.yml.j2
    dest: '{{ home_root }}/{{ item }}/.esmvaltool/config-user.yml'
    mode: '0644'
    owner: "{{ item }}"
    group: "{{ item }}"
  loop: "{{ myusers.stdout_lines }}"
  loop_control:
    label: "{{ item }}"
  ignore_errors: True

- name: ESMValTool configuration directory in new user skeleton
  file:
    path: '/etc/skel/.esmvaltool'
    state: directory
    mode: '0755'

- name: ESMValTool config-user.yml in new user skeleton
  template:
    src: config-user.yml.j2
    dest: '/etc/skel/.esmvaltool/config-user.yml'
    mode: '0644'

- name: Create esmvaltool downloads dir
  file:
    path: '/etc/skel/.esmvaltool/downloads'
    state: directory
    mode: '0755'

- name: ewaterycle.yaml
  template:
    src: ewatercycle.yaml.j2
    dest: /etc/ewatercycle.yaml
    mode: '0644'

- name: conda clean
  # TODO check if cleaning is needed
  command: '{{ conda_root }}/condabin/conda clean -a -y'  # noqa no-changed-when
