---
# tasks file for ewatercycle

- name: Stage conda env file
  copy:
    src: environment.yml
    dest: '{{ conda_root }}/environment.yml'
    mode: '0644'
- name: Install/update eWaterCycle conda environment
  # TODO mamba installs packages requiring mpi, falling back to conda to get nompi packages?
  # TODO replace with task from ansible galaxy
  command: '{{ conda_root }}/condabin/conda env update --file {{ conda_root }}/environment.yml'  # noqa no-changed-when
- name: eWaterCycle pip dependencies
  pip:
    executable: '{{ conda_root }}/envs/ewatercycle/bin/pip3'
    name:
      - jupyterlab_thredds==0.5.0
      # TODO install ewatercycle from PyPI instead of GH
      - git+https://github.com/eWaterCycle/ewatercycle
- name: Activate eWaterCycle conda environment during login for all posix_users
  lineinfile:
    path: /etc/profile.d/conda.sh
    line: conda activate ewatercycle
    regexp: '^conda activate ewatercycle'

# TODO remove: Disk mounted which already has files
# - name: Data for esmvaltool
#   include: esmvaltool-data.yml

# Checklist system setup https://ewatercycle.readthedocs.io/en/latest/system_setup.html :
# Conda environment -> done on line 10
# Install ewatercycle package -> done on line 18
# Configure ESMValTool -> done on line 42-49
# Download climate data -> mounted on /data/volume_2/esmvaltool
# Install container engine -> done in singularity role
# Configure ewatercycle -> done on line 51-54
# Model container images -> mounted on /data/volume_2/singularity-images
# Download example parameter sets -> mounted on /data/volume_2/parameter-sets
# Prepare other parameter sets -> mounted on /data/volume_2/parameter-sets
# Download example forcing -> mounted on /data/volume_2/forcings
# Download observation data -> mounted on /data/volume_2/observation

# Loop over users in wheel to copy .esmvaltool/config-user.yml using home_root=/home var
- name: List my users
  command: ls -1
  args:
    chdir: '{{ home_root }}'
  register: myusers

- name: Myusers
  debug:
    var: myusers

- name: ESMValTool configuration directory
  file:
    path: '{{ home_root }}/{{ item }}/.esmvaltool'
    state: directory
    mode: '0755'
    owner: "{{ item }}"
    group: "{{ item }}"
  loop: "{{ myusers.stdout_lines }}"
  loop_control:
    label: "{{ item }}"

- name: ESMValTool config-user.yml
  template:
    src: config-user.yml.j2
    dest: '{{ home_root }}/{{ item }}/.esmvaltool/config-user.yml'
    mode: '0644'
    owner: "{{ item }}"
    group: "{{ item }}"
  loop: "{{ myusers.stdout_lines }}"
  loop_control:
    label: "{{ item }}"

- name: ewaterycle.yaml
  template:
    src: ewatercycle.yaml.j2
    dest: /etc/ewatercycle.yaml
    mode: '0644'

- name: conda clean
  # TODO check if cleaning is needed
  command: '{{ conda_root }}/condabin/conda clean -a -y'  # noqa no-changed-when
