---
# tasks file for ewatercycle

- name: Stage conda env file
  copy:
    src: environment.yml
    dest: '{{ conda_root }}/environment.yml'
    mode: '0644'
- name: Install/update eWaterCycle platform conda environment + Jupyter and its extensions
  # TODO replace with task from ansible galaxy
  command: '{{ conda_root }}/condabin/mamba env update --name {{ conda_environment }} --file {{ conda_root }}/environment.yml'  # noqa no-changed-when
- name: Activate eWaterCycle conda environment during login for all posix_users
  lineinfile:
    path: /etc/profile.d/conda.sh
    line: conda activate {{ conda_environment }}
    regexp: '^conda activate {{ conda_environment }}'

# Checklist system setup https://ewatercycle.readthedocs.io/en/latest/system_setup.html :
# Conda environment -> done on line 10
# Install ewatercycle package -> done on line 18
# Configure ESMValTool -> done on line 42-49
# Download climate data -> from dcache mounted on /mnt/data
# Install container engine -> done in singularity role
# Configure ewatercycle -> done on line 51-54
# Model container images -> from dcache mounted on /mnt/data
# Download example parameter sets -> from dcache mounted on /mnt/data
# Prepare other parameter sets -> from dcache mounted on /mnt/data
# Download example forcing -> from dcache mounted on /mnt/data
# Download observation data -> from dcache mounted on /mnt/data

# Loop over users in /home to copy .esmvaltool/config-user.yml using home_root=/home var
- name: List my users
  shell: set -o pipefail && ls -1 | grep -v lost+found
  args:
    chdir: '{{ home_root }}'
  register: myusers
  changed_when: False

- name: Myusers
  debug:
    var: myusers

- name: ESMValTool configuration directory
  file:
    path: '{{ home_root }}/{{ item }}/.esmvaltool'
    state: directory
    mode: '0755'
    owner: "{{ item }}"
    group: "{{ item }}"
  loop: "{{ myusers.stdout_lines }}"
  loop_control:
    label: "{{ item }}"

- name: ESMValTool config-user.yml
  template:
    src: config-user.yml.j2
    dest: '{{ home_root }}/{{ item }}/.esmvaltool/config-user.yml'
    mode: '0644'
    owner: "{{ item }}"
    group: "{{ item }}"
  loop: "{{ myusers.stdout_lines }}"
  loop_control:
    label: "{{ item }}"

- name: ESMValTool configuration directory in new user skeleton
  file:
    path: '/etc/skel/.esmvaltool'
    state: directory
    mode: '0755'

- name: ESMValTool config-user.yml in new user skeleton
  template:
    src: config-user.yml.j2
    dest: '/etc/skel/.esmvaltool/config-user.yml'
    mode: '0644'

- name: ewaterycle.yaml
  template:
    src: ewatercycle.yaml.j2
    dest: /etc/ewatercycle.yaml
    mode: '0644'

- name: conda clean
  # TODO check if cleaning is needed
  command: '{{ conda_root }}/condabin/conda clean -a -y'  # noqa no-changed-when
