---
# tasks file for ewatercycle

- name: Stage conda env file
  copy:
    src: environment.yml
    dest: '{{ conda_root }}/environment.yml'

- name: Install eWaterCycle conda environment
  command: '{{ conda_root }}/condabin/mamba env update --file {{ conda_root }}/environment.yml'

- name: eWaterCycle pip dependencies
  pip:
    executable: '{{ conda_root }}/envs/ewatercycle/bin/pip3'
    name:
      - jupyterlab_thredds==0.5.0
      # TODO install ewatercycle from PyPI instead of GH
      - git+https://github.com/eWaterCycle/ewatercycle
- name: Activate eWaterCycle conda environment during login for all posix_users
  lineinfile:
    path: /etc/profile.d/conda.sh
    line: conda activate ewatercycle
    regexp: '^conda activate ewatercycle'
- name: Data for esmvaltool
  include: esmvaltool-data.yml
