---
# tasks file for ewatercycle
- name: Install ewatercycle conda environment
  conda:
    executable: '{{ conda_root }}/condabin/conda'
    environment: ewatercycle
    channels:
      - esmvalgroup
      - conda-forge
    name:
      - python=3.7.7
      - ipykernel=5.3.1
      - altair_saver=0.5.0
      - altair=4.1.0
      - autopep8=1.5.3
      - black=19.10b0
      - dask-jobqueue=0.7.1
      - dask-labextension=2.0.2
      - distributed=2.20.0
      - esmvaltool-python=2.0.0b4
      - flake8=3.8.3
      - geoviews=1.8.1
      - hydrostats=0.78
      - ipyleaflet=0.13.1
      - ipympl=0.5.6
      - ipynb-py-convert=0.4.5
      - isort=4.3.21
      - jupyter-server-proxy=1.5.0
      - jupyterhub=1.1.0
      - jupyterlab_code_formatter=1.3.1
      - jupyterlab=2.1.5
      - pylint=2.5.3
      - pymt_cem=0.1.3
      - pymt_ecsimplesnow=0.2.5
      - pymt_gipl=0.1
      - pymt_hydrotrend=0.1.2
      - pymt_landlab=0.3.0
      - pymt_permamodel=0.1.3
      - pymt_rafem=0.1.4
      - pymt_sedflux=0.1.3
      - pymt=1.1.3
      - regionmask=0.5.0
      - setuptools=47.3.1
      - yapf=0.30.0
      # - pymt_child  # Skipped as only a osx binary is available
      # - pymt_topoflow  # Skipped not on conda-forge
      # Everything below is installed via dependencies but kept here for version reference
      - bokeh=2.1.1
      - cartopy=0.18.0
      - cf-units=2.1.4
      - cftime=1.2.0
      - cython=0.29.20
      - dask=2.20.0
      - datashader=0.11.0
      - ecmwf-api-client=1.5.4
      - eofs=1.4.0
      - holoviews=1.13.3
      - iris=2.4.0
      - joblib=0.16.0
      - matplotlib=3.2.2
      - nc-time-axis=1.2.0
      - notebook=6.0.3
      - numpy=1.18.5
      - pip=20.1.1
      - python-cdo=1.5.3
      - scikit-learn=0.23.1
      - seaborn=0.10.1
      - threadpoolctl=2.1.0
      - tqdm=4.47.0
      - xarray=0.15.1
      - xesmf=0.3.0
      - xlrd=1.2.0
      - xlsxwriter=1.2.9
      - pyke==1.1.1  # required by iris, only available on conda or sourceforge
- name: eWatercycle pip dependencies
  pip:
    executable: '{{ conda_root }}/envs/ewatercycle/bin/pip3'
    name:
      - jupyterlab_thredds==0.5.0
      - grpc4bmi==0.2.6
      - git+https://github.com/eWaterCycle/parametersetdb.git@observation_data
- name: Jupyter server code formatter extension
  copy:
    src: jupyterlab_code_formatter.json
    dest: '{{ conda_root }}/envs/ewatercycle/etc/jupyter/jupyter_notebook_config.d/jupyterlab_code_formatter.json'
- name: eWaterCycle uninstall obsolete lab extensions
  command: '{{ conda_root }}/envs/ewatercycle/bin/jupyter labextension uninstall {{ jupyterlab_obsolete_extensions }}'
- name: eWaterCycle install lab extensions
  command: '{{ conda_root }}/envs/ewatercycle/bin/jupyter labextension install {{ jupyterlab_extensions }}'
- name: Activate ewatercycle conda environment during login for all posix_users
  lineinfile:
    path: ~/.bashrc
    line: conda activate ewatercycle
    regexp: '^conda activate ewatercycle'
  become: yes
  become_user: "{{ item.name }}"
  loop: "{{ posix_users }}"
  loop_control:
    label: "{{ item.name }}"
