---
name: ewatercycle
channels:
  - conda-forge
  - defaults
dependencies:
  # TODO pin versions for reproducibility. Use `conda env export` and `pip list` to get versions
  - python==3.10
  - subversion # for ewatercycle.parameter_sets
  - esmvaltool-python>=2.3.0
  # Pin esmpy so we dont get forced to run all parallel tasks on single cpu
  # Can be removed once https://github.com/ESMValGroup/ESMValCore/issues/1208 is resolved.
  - esmpy!=8.1.0,<8.4
  # Line above are copy from https://github.com/eWaterCycle/ewatercycle/blob/main/environment.yml
  - ansible
  - pip:
      - typeguard<3  # Pinned for eWatercycle 1.4.1 compatibility.
      - ewatercycle
      - era5cli
  - setuptools
  - altair_saver
  - altair
  - dask-jobqueue
  - distributed
  - geoviews
  - hydrostats
  - nco
  - ncview
  - regionmask
  - pyke  # required by iris, only available on conda or sourceforge
  - iris-sample-data # for sample notebooks, see https://github.com/eWaterCycle/notebooks/issues/15
  # Pangeo deps, see https://pangeo.io/setup_guides/hpc.html
  - zarr
  - hvplot
  - numcodecs
  # Lint / formatters
  - autopep8
  - black
  - flake8
  - isort
  - pylint
  - yapf
  # Pymt
  - pymt_cem
  - pymt_ecsimplesnow
  - pymt_gipl
  - pymt_hydrotrend
  - pymt_landlab
  - pymt_permamodel
  - pymt_rafem
  - pymt_sedflux
  - pymt
  # - pymt_child  # Skipped as only a osx binary is available
  # - pymt_topoflow  # Skipped not on conda-forge
  # Jupyter
  - jupyter-server-proxy
  - jupyterhub
  - jupyterlab # Version pinned due to not all wanted extensions support v3
  - notebook
  - ipykernel
  - ipympl
  - ipynb-py-convert
  - jupyterhub-idle-culler
  - jupyterhub-systemdspawner
  # JupyterLab extensions server dependencies, lab extension should be added to defaults of jupyter role
  - ipyleaflet
  - jupyterlab_code_formatter
  - dask-labextension
  - jupyterlab-geojson
  - jupyter_bokeh
  - pyviz_comms
  - jupyterlab-git
  - nbdime
  - nbgitpuller
  - papermill
