
---
name: ewatercycle
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - setuptools
  - altair_saver
  - altair
  - dask-jobqueue
  - distributed
  - esmvaltool-python
  - geoviews
  - hydrostats
  - nco
  - ncview
  - regionmask
  - pyke  # required by iris, only available on conda or sourceforge
  - iris-sample-data # for sample notebooks, see https://github.com/eWaterCycle/notebooks/issues/15
  - subversion # for ewatercycle.parameter_sets
  # Lint / formatters
  - autopep8
  - black
  - flake8
  - isort
  - pylint
  - yapf
  # Pymt
  - pymt_cem
  - pymt_ecsimplesnow
  - pymt_gipl
  - pymt_hydrotrend
  - pymt_landlab
  - pymt_permamodel
  - pymt_rafem
  - pymt_sedflux
  - pymt
  # - pymt_child  # Skipped as only a osx binary is available
  # - pymt_topoflow  # Skipped not on conda-forge
  # Jupyter
  - jupyter-server-proxy
  - jupyterhub
  - jupyterlab=2.3.1 # Version pinned due to not all wanted extensions support v3
  - notebook
  - ipykernel
  - ipympl
  - ipynb-py-convert
  - jupyterhub-idle-culler
  # JupyterLab extensions server dependencies, lab extension should be added to defaults of jupyter role
  - ipyleaflet
  - jupyterlab_code_formatter
  - dask-labextension
  - nbgitpuller
  # TODO pin versions of deps of deps
  # Everything below is installed via dependencies but kept here for version reference
  # - bokeh=2.3.0
  # - cartopy=0.18.0
  # - cfunits=3.3.1
  # - cftime=1.2.1
  # - cython=0.29.22
  # - dask=2.20.0
  # - datashader=0.12.1
  # - ecmwf-api-client=1.6.1
  # - eofs=1.4.0
  # - holoviews=1.14.2
  # - hvplot=0.7.1
  # - iris=3.0.1
  # - joblib=1.0.1
  # - matplotlib=3.4.1
  # - nc-time-axis=1.2.0
  # - numpy=1.20.2
  # - pip=21.0.1
  # - python-cdo=1.5.4
  # - scikit-learn=0.24.1
  # - seaborn=0.11.1
  # - threadpoolctl=2.1.0
  # - tqdm=4.60.0
  # - xarray=0.17.0
  # - xesmf=0.5.2
  # - xlsxwriter=1.3.8
# TODO add jupyterlab-git==0.30.0b3 and nbdime see https://gitlab.com/rsc-surf-nl/rsc-plugins/-/blob/master/ansible/application-jupyter/application-jupyter.yml

# TODO mpi versions of hdf5 are installed causing libmpi not found errors
