---
- name: Install ipykernel
  conda:
    name: ipykernel
    channels: conda-forge
- name: Register Jupyter kernel
  command: '{{ conda_root }}/bin/python -m ipykernel install --name=conda --display-name="Python 3 (Conda)" --prefix=/usr/local'
  args:
    creates: /usr/local/share/jupyter/kernels/conda
- name: Set PROJ_LIB and PATH env vars in Jupyter conda kernel
  template:
    src: conda-kernel.json.j2
    dest: /usr/local/share/jupyter/kernels/conda/kernel.json
  notify: restart jupyterhub
