---
- name: Docker Python package
  pip:
    name: docker
    executable: pip3
- name: Remove old Docker-py python package
  pip:
    name: docker-py
    state: absent
- name: grpc4bmi Docker images
  docker_image:
    name: '{{ item.docker }}'
    source: pull
  loop: '{{ grpc4bmi_images }}'
- name: Singularity image dir
  file:
    path: '{{ singularity_image_root }}'
    state: directory
- name: grpc4bmi Singularity images
  command: singularity build {{ singularity_image_root }}/{{ item.singularity }} docker://{{ item.docker }}
  args:
    creates: '{{ singularity_image_root }}/{{ item.singularity }}'
  loop: '{{ grpc4bmi_images }}'
- name: USGS data home directory
  file:
    path: '{{ jupyterhub_spawner_environment.USGS_DATA_HOME }}'
    state: directory
    mode: 0775
    group: jupyter
