---
- name: Docker Python package
  pip:
    name: docker
    executable: pip3
- name: Remove old Docker-py python2 package
  pip:
    name: docker-py
    state: absent
- name: Remove old Docker-py python3 package
  pip:
    name: docker-py
    state: absent
    executable: pip3
- include: singularity-images.yml
- name: USGS data home directory
  file:
    path: '{{ jupyterhub_spawner_environment.USGS_DATA_HOME }}'
    state: directory
    mode: 0775
    group: jupyter
