---
- name: parametersetdb dependencies
  apt:
    name: subversion
- name: parametersetdb
  pip:
    executable: pip3
    name: git+https://github.com/eWaterCycle/parametersetdb.git@{{ parametersetdb_version }}
    state: latest
- name: grpc4bmi
  pip:
    executable: pip3
    name: grpc4bmi=={{ grpc4bmi_version }}
- name: grpc4bmi Docker images
  docker_image:
    name: '{{ item.docker }}'
  loop: '{{ grpc4bmi_images }}'
- name: Singularity image dir
  file:
    path: '{{ singularity_image_root }}'
    state: directory
- name: grpc4bmi Singularity images
  command: singularity build {{ singularity_image_root }}/{{ item.singularity }} docker://{{ item.docker }}
  args:
    creates: '{{ singularity_image_root }}/{{ item.singularity }}'
  loop: '{{ grpc4bmi_images }}'
- name: USGS data home directory
  file:
    path: '{{ jupyterhub_spawner_environment.USGS_DATA_HOME }}'
    state: directory
    mode: 0775
    group: jupyter
