---
- name: Allow Jupyter server internal traffic
  ufw:
    rule: allow
    port: 8081
    proto: tcp
    from_ip: 172.17.0.0/12
- name: JupyterHub systemd file
  copy:
    src: jupyterhub.systemd
    dest: /etc/systemd/system/jupyterhub.service
- name: Install JupyterHub
  pip:
    executable: pip3
    name: "{{ item }}"
  loop:
    - setuptools==40.8.0
    - jupyterhub==0.9.4
  notify:
    - restart jupyterhub
- name: Allow posix_users to use docker
  user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    groups: docker
    home: /mnt/home/{{ item.name }}
    shell: /bin/bash
  loop: "{{ posix_users }}"
- name: NodeJS ppa key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
- name: NodeJS ppa
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_8.x xenial main'
- name: NodeJS
  apt:
    name: nodejs
    update_cache: yes
- name: NodeJS dependencies for JupyterHub
  npm:
    global: yes
    name: configurable-http-proxy
- name: Create /etc/jupyterhub directory
  file:
    path: /etc/jupyterhub
    state: directory
- name: cull_idle_servers
  get_url:
    url: https://github.com/jupyterhub/jupyterhub/raw/master/examples/cull-idle/cull_idle_servers.py
    dest: /usr/local/bin/cull_idle_servers.py
    mode: 755
    checksum: sha256:4704b2db1ba4df56603ca8420271e71576647edceda8fa8552e258d011de49b7
- name: jupyterhub_config
  template:
    src: jupyterhub_config.py.j2
    dest: /etc/jupyterhub/jupyterhub_config.py
  notify:
    - restart jupyterhub