---
- name: Allow Jupyter server internal traffic
  ufw:
    rule: allow
    port: 8081
    proto: tcp
    from_ip: 172.17.0.0/12
- name: JupyterHub systemd file
  template:
    src: jupyterhub.systemd.j2
    dest: /etc/systemd/system/jupyterhub.service
- name: jupyterhub service enabled
  systemd:
    name: jupyterhub
    state: reloaded
    daemon_reload: yes
    enabled: yes
- name: jupyter posix group
  group:
    name: jupyter
    state: present
- name: Create users for Jupyter Hub with Docker permission
  user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    groups:
      - docker
      - jupyter
    home: /mnt/home/{{ item.name }}
    shell: /bin/bash
  loop: "{{ posix_users }}"
  loop_control:
    label: "{{ item.name }}"
- name: Allow ssh login with password
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication yes'
  notify:
    - restart ssh
- name: NodeJS dependencies for JupyterHub
  npm:
    global: yes
    name: configurable-http-proxy
    executable: '{{ conda_environment_bin }}/npm'
- name: Create /etc/jupyterhub directory
  file:
    path: /etc/jupyterhub
    state: directory
- name: cull_idle_servers
  get_url:
    url: https://github.com/jupyterhub/jupyterhub/raw/master/examples/cull-idle/cull_idle_servers.py
    dest: /usr/local/bin/cull_idle_servers.py
    mode: 755
    checksum: sha256:746e60ce0e8fc0a575e96a7362947ca43295f426f4c3d73f5e3d4ac0244df3a3
- name: jupyterhub_config
  template:
    src: jupyterhub_config.py.j2
    dest: /etc/jupyterhub/jupyterhub_config.py
  notify:
    - restart jupyterhub
- name: Restart jupyterhub when cert has been renewed
  copy:
    src: certbot-deploy.sh
    dest: /etc/letsencrypt/renewal-hooks/deploy/jupyterhub-restart
    mode: 0755
- name: Remove default conda python kernel
  command: /mnt/apps/conda/envs/ewatercycle/bin/jupyter kernelspec remove -f conda
  args:
    removes: /usr/local/share/jupyter/kernels/conda
  notify:
    - restart jupyterhub
- name: Jupyter server code formatter extension
  copy:
    src: jupyterlab_code_formatter.json
    dest: '{{ conda_root }}/envs/ewatercycle/etc/jupyter/jupyter_notebook_config.d/jupyterlab_code_formatter.json'
- name: eWaterCycle uninstall obsolete lab extensions
  command: '{{ conda_root }}/envs/ewatercycle/bin/jupyter labextension uninstall {{ jupyterlab_obsolete_extensions }}'
- name: eWaterCycle install lab extensions
  command: '{{ conda_root }}/envs/ewatercycle/bin/jupyter labextension install {{ jupyterlab_extensions }}'
