---
- name: Allow Jupyter server internal traffic
  ufw:
    rule: allow
    port: 8081
    proto: tcp
    from_ip: 172.17.0.0/12
- name: JupyterHub systemd file
  template:
    src: jupyterhub.systemd.j2
    dest: /etc/systemd/system/jupyterhub.service
- name: jupyterhub service enabled
  systemd:
    name: jupyterhub
    state: reloaded
    daemon_reload: yes
    enabled: yes
- name: jupyter posix group
  group:
    name: jupyter
    state: present
- name: Grant users Docker permission
  user:
    name: "{{ item.name }}"
    groups:
      - docker
      - jupyter
  loop: "{{ posix_users }}"
  loop_control:
    label: "{{ item.name }}"
- name: Allow ssh login with password
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication yes'
  notify:
    - restart ssh
- name: NodeJS dependencies for JupyterHub
  npm:
    global: yes
    name: configurable-http-proxy
    executable: '{{ conda_environment_bin }}/npm'
  environment:
        PATH: "{{ conda_environment_bin }}:{{ ansible_env.PATH }}"
- name: Create /etc/jupyterhub directory
  file:
    path: /etc/jupyterhub
    state: directory
- name: jupyterhub_config
  template:
    src: jupyterhub_config.py.j2
    dest: /etc/jupyterhub/jupyterhub_config.py
  notify:
    - restart jupyterhub
- name: Restart jupyterhub when cert has been renewed
  copy:
    src: certbot-deploy.sh
    dest: /etc/letsencrypt/renewal-hooks/deploy/jupyterhub-restart
    mode: 0755
- name: Remove default conda python kernel
  command: /mnt/apps/conda/envs/ewatercycle/bin/jupyter kernelspec remove -f conda
  args:
    removes: /usr/local/share/jupyter/kernels/conda
  notify:
    - restart jupyterhub
