---
# tasks file for jupyterlab
- name: Jupyterlab
  block:
    - name: Jupyterlab apt dependencies
      apt:
        update_cache: yes
        name:
          - libcairo2-dev
          - libjpeg-dev
          - libpango1.0-dev
          - libgif-dev
          - build-essential
          - g++
          - python3-dev
          - libgeos-dev
          - libgdal-dev
          - libproj-dev
          - libudunits2-dev
          - cdo
          - netcdf-bin
          - nco
          - gdal-bin
          - libspatialindex-c4v5
          - tmux
    - name: Cython
      pip:
        executable: pip3
        name: cython==0.29.4
    - name: Numpy
      pip:
        executable: pip3
        name: numpy==1.16.1
    - name: Cartopy, without pep517
      pip:
        executable: pip3
        name: cartopy==0.17.0
        extra_args: --no-use-pep517
    - name: Jupyterlab python dependencies
      pip:
        executable: pip3
        name:
          - dask==1.1.1
          - 'https://downloads.sourceforge.net/project/pyke/pyke/1.1.1/pyke3-1.1.1.zip?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fpyke%2Ffiles%2Fpyke%2F1.1.1%2Fpyke3-1.1.1.zip%2Fdownload&ts=1537463129#egg=pyke'  # noqa 204
          - cf_units==2.1.1
          - cftime==1.0.3.4
          - jupyterlab==2.1.5
          - ipyleaflet==0.13.1
          - bokeh==2.1.1
          - holoviews==1.13.3
          - geoviews==1.8.1
          - xarray==0.11.3
          - nc_time_axis==1.1.0
          - notebook==6.0.3
# TODO jupyterlab_thredds incompatible with JupyterLab v2
#          - jupyterlab_thredds==0.3.0
          - datashader==0.6.9
          - ipympl==0.5.6
          - tqdm==4.30.0
          - scitools-iris==2.2.0
          - hydrostats==0.75
          - black==19.10b0
          - yapf==0.30.0
          - isort==4.3.21
          - autopep8==1.5.3
          - jupyterlab_code_formatter==1.3.1
          - flake8==3.8.3
- name: Jupyter server code formatter extension
  copy:
    src: jupyterlab_code_formatter.json
    dest: /usr/local/etc/jupyter/jupyter_notebook_config.d/jupyterlab_code_formatter.json
- name: Jupyterlab uninstall obsolete extensions
  command: jupyter labextension uninstall {{ jupyterlab_obsolete_extensions }}
- name: Jupyterlab extensions
  command: jupyter labextension install {{ jupyterlab_extensions }}
