---
- name: Jupyter Hub
  include: hub.yml
# - name: Jupyter Lab
#   include: lab.yml
- name: Sample notebooks
  include: samples.yml
- name: grpc4bmi
  include: grpc4bmi.yml
- name: conda
  include: conda.yml
