---
- name: Jupyter Hub
  include: hub.yml
- name: Jupyter Lab
  include: lab.yml
# TODO replace with github.com/ewatercycle/ewatercycle/docs/examples
# - name: Sample notebooks
#   include: samples.yml
- name: grpc4bmi
  include: grpc4bmi.yml
