---
- name: Sync sample notebooks repo
  # TODO replace with examples from https://github.com/eWaterCycle/ewatercycle
  git:
    repo: https://github.com/eWaterCycle/notebooks.git
    version: "{{ sample_notebooks_version }}"
    dest: /mnt/apps/sample-notebooks
    depth: 1
- name: Copy sample notebooks to home directories
  copy:
    src: /mnt/apps/sample-notebooks
    dest: /mnt/home/{{ item.name }}/
    remote_src: yes
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    force: no # some users have started editing the samples, they will not get updated notebooks
  loop: "{{ posix_users }}"
  loop_control:
    label: "{{ item.name }}"
