---
- name: Copy sample notebooks to home directories
  git:
    repo: https://github.com/eWaterCycle/notebooks.git
    version: "{{ sample_notebooks_version }}"
    dest: /mnt/home/{{ item.name }}/sample-notebooks
  loop: "{{ posix_users }}"
  ignore_errors: yes  # some users have started editing the samples, they will not get updated notebooks
- name: Chown sample notebooks
  file:
    path: /mnt/home/{{ item.name }}/sample-notebooks
    group: "{{ item.name }}"
    owner: "{{ item.name }}"
    recurse: yes
    state: directory
  loop: "{{ posix_users }}"
