---
- name: Singularity image dir
  file:
    path: '{{ singularity_image_root }}'
    state: directory
- name: grpc4bmi Singularity images
  command: singularity build {{ singularity_image_root }}/{{ item.singularity }} docker://{{ item.docker }}
  args:
    creates: '{{ singularity_image_root }}/{{ item.singularity }}'
  loop: '{{ grpc4bmi_images }}'
