- name: Ubuntu user
  user:
    name: ubuntu
- name: Authorized keys for ubuntu user
  authorized_key:
    user: ubuntu
    state: present
    key: '{{ item }}'
  loop: '{{ authorized_keys }}'
  tags:
   - ssh
