---
- name: Ufw firewall command must be present
  ansible.builtin.apt:
    name: ufw
    state: present
- name: Allow ssh from anywhere
  community.general.ufw:
    rule: limit
    name: OpenSSH
- name: Allow http + https traffic
  community.general.ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  loop:
    - 80
    - 443
- name: Deny all other incoming traffic
  community.general.ufw:
    state: enabled
    policy: deny
    direction: incoming
