---
- name: Hostname prerequisites
  ansible.builtin.apt:
    update_cache: true
    name: "dbus"
- name: Set hostname
  ansible.builtin.hostname: 
    name: "{{ inventory_hostname }}"
  when: not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')
- name: Add myself to /etc/hosts
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ansible_default_ipv4.address }}.+$"
    line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"
    state: present
