---
# tasks file for storage
- name: Move /home from root disk to other disk
  include_tasks: home.yml
- name: Mount data from Samba share
  include_tasks: data-samba.yml
  when: shared_data_source == 'samba' and samba_password is defined
- name: Mount data from dcache
  include_tasks: data-dcache.yml
  when: shared_data_source == 'dcache'
