---
# URL of JupyterHub server
jupyterhub_url: /jupyter
# version|commit of https://github.com/eWaterCycle/experiment-launcher
launcher_version: ead304d497bdadc622231a2a33ec93803beee20d
# Under which uri path the launcher is running
launcher_base_path: /launcher
