---
- name: amuse-framework - git
  git:
    repo: https://github.com/eWaterCycle/amuse-framework.git
    dest: /mnt/apps/amuse-framework
    version: '{{ amuse_version }}'
    depth: 1
    force: yes
  notify:
   - Clean amuse-framework
- name: amuse-framework - apt deps
  apt:
    update_cache: yes
    pkg:
      - build-essential
      - curl
      - g++
      - gfortran
      - gettext
      - zlib1g-dev
      - libopenmpi-dev
      - openmpi-bin
      - libfftw3-3
      - libfftw3-dev
      - libmpfr6
      - libmpfr-dev
      - libhdf5-serial-dev
      - libgsl-dev
- name: amuse-framework - Python deps
  pip:
    executable: '{{ conda_environment_bin }}/pip3'
    name:
      - mpi4py==3.0.0
      - docutils==0.14
      - nose==1.3.7
      - h5py==2.8.0
- name: amuse-framework - configure
  command: ./configure
  args:
    chdir: /mnt/apps/amuse-framework
    creates: /mnt/apps/amuse-framework/config.mk
  environment:
    PYTHON: '{{ conda_environment_bin }}/python3'
- name: amuse-framework - install
  make:
    target: install
    chdir: /mnt/apps/amuse-framework
- name: hymuse - repo
  git:
    repo: https://github.com/eWaterCycle/HyMUSE.git
    dest: /mnt/apps/HyMUSE
    version: '{{ hymuse_version }}'
    depth: 1
    force: yes
  notify:
   - Clean HyMUSE build
   - Clean HyMUSE install
- name: hymuse - build
  command: '{{ conda_environment_bin }}/python3 setup.py build'
  args:
    chdir: /mnt/apps/HyMUSE
    creates: /mnt/apps/HyMUSE/build
  environment:
    DOWNLOAD_CODES: '1'
- name: hymuse - install
  command: '{{ conda_environment_bin }}/python3 setup.py install'
  args:
    chdir: /mnt/apps/HyMUSE
    creates: /usr/local/lib/python3.6/dist-packages/hymuse
