---
# tasks file for docker
- name: Docker ppa key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Docker ppa
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable'
- name: Update apt cache
  apt: update_cache=yes
- name: Docker
  apt:
    name: docker-ce
- name: Create docker root
  file:
    path: "{{ docker_root }}"
    state: directory
  when: docker_root is defined
- name: docker daemon.json
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify:
    - restart docker
  when: docker_root is defined
