---
- name: Converge
  hosts: all
  tasks:
    - name: Installing pip3 as Ubuntu docker image does not ship with it
      package:
        name: python3-pip
    - name: Installing setuptools so Ansible modules work
      package:
        name: python-setuptools
    - include_role:
        name: launcher
      vars:
        launcher_encrypted: false
        launcher_jupyterhub_token: 297cee229574135ae2f6721d9b3f0b9dd138c831cc15084c01d68f145b70b5b2
        jupyterhub_url: https://hub.example.com
