---
- name: Converge
  hosts: all
  tasks:
    - name: Installing pip3 as Ubuntu docker image does not ship with it
      package:
        name: python3-pip
    - name: Installing setuptools so Ansible modules work
      package:
        name: python-setuptools
    - name: Launcher role
      include_role:
        name: launcher
      vars:
        jupyterhub_url: https://hub.example.com
