---
- name: Install ipykernel
  command: '{{ conda_root }}/bin/conda install -q -y -c conda-forge ipykernel'
  args:
    creates: '{{ conda_root }}/lib/python3.7/site-packages/ipykernel'
- name: Register Jupyter kernel
  command: '{{ conda_root }}/bin/python -m ipykernel install --name=conda --display-name="Python 3 (Conda)" --prefix={{ conda_jupyter_prefix }}'
  args:
    creates: '{{ conda_jupyter_prefix }}/share/jupyter/kernels/conda'
- name: Set PROJ_LIB and PATH env vars in Jupyter conda kernel
  lineinfile:
    path: '{{ conda_jupyter_prefix }}/share/jupyter/kernels/conda/kernel.json'
    regexp: '\"env'
    line: '"env": {"PROJ_LIB": "{{ conda_root }}/share/proj", "PATH": "{{ conda_root }}/bin:{{ conda_root }}/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"},'
    insertafter: '\{'
  notify: restart jupyterhub