---
- name: Download miniconda tarball
  get_url:
    url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    dest: /mnt/apps/
    checksum: '{{ miniconda_tarball_checksum }}'
- name: Install conda
  command: /bin/bash Miniconda3-latest-Linux-x86_64.sh -f -b -p /mnt/apps/conda
  args:
    chdir: /mnt/apps
    creates: /mnt/apps/conda
- name: Update conda
  command: /mnt/apps/conda/bin/conda update -q -y -n base -c defaults conda
- name: Jupyter kernel registration
  include: jupyter.yml
  when: register_jupyter_kernel
