---
- name: Download miniconda tarball
  get_url:
    url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    dest: '{{ conda_tarball_root }}/'
    checksum: '{{ conda_tarball_checksum }}'
- name: Install conda
  command: /bin/bash {{ conda_tarball_root }}/Miniconda3-latest-Linux-x86_64.sh -f -b -p {{ conda_root }}
  args:
    creates: '{{ conda_root }}'
- name: conda in PATH
  file:
    src: '{{ conda_root }}/bin/conda'
    dest: /usr/local/bin/conda
    state: link
- name: Add conda init to bash profiles
  command: conda init
  become: yes
  become_user: "{{ item.name }}"
  loop: "{{ posix_users }}"
  loop_control:
    label: "{{ item.name }}"