galaxy_info:
  author: Stefan Verhoeven
  namespace: ewatercycle
  description: Apptainer installation
  company: Netherlands eScience Center
  license: Apache-2.0
  min_ansible_version: '2.1'
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags: []
dependencies: []
