---
cull:
  # Servers and notebooks that have been idle for longer then timeout (in seconds) will be culled.
  timeout: '86400' # 1 day
  # The maximum age (in seconds) of servers that should be culled even if they are active.
  max_age: '604800' # 7 days
jupyterhub_spawner_environment:
  # Cache dir for ewatercycle.observation.usgs.get_usgs_data()
  USGS_DATA_HOME: /tmp
  # TODO needed for pymt(?) and cfunits
  UDUNITS2_XML_PATH: /usr/share/xml/udunits/udunits2.xml
  # Make proj work in notebook, if not set get `ERROR 1: PROJ: proj_create_from_database: Open of /opt/conda/envs/ewatercycle/share/proj failed` error
  PROJ_LIB: '{{ conda_root }}/envs/{{ conda_environment }}/share/proj'
  ESMFMKFILE: '{{ conda_root }}/envs/{{ conda_environment }}/lib/esmf.mk'
# Location where conda is installed
conda_root: /opt/conda
# Name of conda environment to use
conda_environment: ewatercycle
# Path to conda environments bin directory
conda_environment_bin: '{{ conda_root }}/envs/{{ conda_environment }}/bin'
# List of posix users who should have JupyterHub admin rights
jupyterhub_admins: []
