---
sample_notebooks_version: '0.1.0'
grpc4bmi_version: '0.2.6'
parametersetdb_version: 'observation_data'
cull:
  timeout: '3600' # 1 hour
  max_age: '86400' # 1 day
# Directory where singularity sif files can be stored and read by other
singularity_image_root: /mnt/apps/singularity-images
# Container images that will be downloaded and converted
grpc4bmi_images:
    - docker: ewatercycle/walrus-grpc4bmi
      singularity: ewatercycle-walrus-grpc4bmi.sif
    - docker: ewatercycle/pcrg-grpc4bmi
      singularity: ewatercycle-pcrg-grpc4bmi.sif
    - docker: ewatercycle/wflow-grpc4bmi
      singularity: ewatercycle-wflow-grpc4bmi.sif
    - docker: sverhoeven/marrmot
      singularity: marrmot.sif
jupyterhub_spawner_environment:
  USGS_DATA_HOME: /mnt/data/usgs/streamflow
  GRDC_DATA_HOME: /mnt/data/grdc/dailies
# Location where conda is installed
conda_root: /mnt/apps/conda
# JupyterLab extensions that should be installed, space seperated list
jupyterlab_extensions: >
  @bokeh/jupyter_bokeh@2.0.2
  @jupyter-widgets/jupyterlab-manager@2.0.0
  @jupyterlab/geojson-extension@v2.0.1
  @jupyterlab/hub-extension@2.1.2
  @jupyterlab/toc@4.0.0
  @pyviz/jupyterlab_pyviz@1.0.4
  jupyter-leaflet@0.13.1
  jupyter-matplotlib@0.7.2
  @ewatercycle/jupyterlab_thredds@0.5.0
# JupyterLab extensions that should not be installed, space seperated list
jupyterlab_obsolete_extensions: >
  @ewatercycle/jupyterlab_thredds
  jupyterlab_bokeh
