---
sample_notebooks_version: '0.1.0'
cull:
  timeout: '3600' # 1 hour
  max_age: '86400' # 1 day
# Directory where singularity sif files can be stored and read by other
singularity_image_root: /mnt/apps/singularity-images
# Container images that will be downloaded and converted
grpc4bmi_images:
    # - docker: ewatercycle/walrus-grpc4bmi
    #   singularity: ewatercycle-walrus-grpc4bmi.sif
    - docker: ewatercycle/pcrg-grpc4bmi:setters
      singularity: ewatercycle-pcrg-grpc4bmi-setters.sif
    - docker: ewatercycle/wflow-grpc4bmi:2020.1.1
      singularity: ewatercycle-wflow-grpc4bmi_2020.1.1.sif
    - docker:  ewatercycle/marrmot-grpc4bmi:2020.11
      singularity: ewatercycle-marrmot-grpc4bmi_2020.11.sif
    # - docker: ewatercycle/hype-grpc4bmi
    #   singularity: ewatercycle-hype-grpc4bmi.sif
    - docker: ewatercycle/lisflood-grpc4bmi:20.10
      singularity: ewatercycle-lisflood-grpc4bmi_20.10.sif
jupyterhub_spawner_environment:
  # Cache dir for ewatercycle.observation.usgs.get_usgs_data()
  USGS_DATA_HOME: /mnt/data/usgs/streamflow
  # Cache dir for ewatercycle.observation.grdc.get_grdc_data()
  GRDC_DATA_HOME: /mnt/data/grdc/dailies
  # TODO needed for pymt(?) and cfunits
  UDUNITS2_XML_PATH: /usr/share/xml/udunits/udunits2.xml
# Location where conda is installed
conda_root: /mnt/apps/conda
conda_environment: ewatercycle
conda_environment_bin: '{{ conda_root}}/envs/{{ conda_environment }}/bin'
# JupyterLab extensions that should be installed, space seperated list
# Server side dependencies of extension should be added to conda environment in ewatercycle role
jupyterlab_extensions: >
  @bokeh/jupyter_bokeh@2.0.2
  @jupyter-widgets/jupyterlab-manager@2.0.0
  @jupyterlab/geojson-extension@v2.0.1
  @jupyterlab/hub-extension@2.1.2
  @jupyterlab/toc@4.0.0
  @pyviz/jupyterlab_pyviz@1.0.4
  jupyter-leaflet@0.13.1
  jupyter-matplotlib@0.7.2
  @ryantam626/jupyterlab_code_formatter@1.3.1
  @ewatercycle/jupyterlab_thredds@0.5.0
  @jupyterlab/server-proxy
  dask-labextension
# JupyterLab extensions that should not be installed, space seperated list
jupyterlab_obsolete_extensions: >
  jupyterlab_bokeh
