---
sample_notebooks_version: '0.1.0'
grpc4bmi_version: '0.2'
parametersetdb_version: '8a8fe1a703efdbdf1b70d1c626810b36f707b50f'
cull:
  timeout: '3600' # 1 hour
  max_age: '86400' # 1 day
# Directory where singularity sif files can be stored and read by other
singularity_image_root: /mnt/apps/singularity-images
# Container images that will be downloaded and converted
grpc4bmi_images:
    - docker: ewatercycle/walrus-grpc4bmi
      singularity: ewatercycle-walrus-grpc4bmi.sif
    - docker: ewatercycle/pcrg-grpc4bmi
      singularity: ewatercycle-pcrg-grpc4bmi.sif
    - docker: ewatercycle/wflow-grpc4bmi
      singularity: ewatercycle-wflow-grpc4bmi.sif
