---
# tasks file for letsencrypt
- name: Certbot ppa
  apt_repository:
    repo: ppa:certbot/certbot
- name:  Certbot
  apt:
    name: certbot
    update_cache: yes
- name: rsync, required for synchronize tasks
  apt:
    name: rsync
- name: Check letsencrypt
  stat:
    path: /etc/letsencrypt/live/{{ inventory_hostname }}/privkey.pem
  register: privcert
- name: Check local letsencrypt cache
  delegate_to: localhost
  stat:
    path: "{{ letsencrypt_backup_root }}/{{ inventory_hostname }}/live/{{ inventory_hostname }}/privkey.pem"
  register: localprivcert
- name: CertBot from cache
  synchronize:
    src: "{{ letsencrypt_backup_root }}/{{ inventory_hostname }}/"
    dest: /etc/letsencrypt/
    recursive: yes
  when: not privcert.stat.exists and localprivcert.stat.exists and not selfsigned
- name: CertBot
  command: >
    certbot certonly --standalone --preferred-challenges http
     --non-interactive -d {{ inventory_hostname }} --agree-tos --email {{ certbot_email }}
  args:
    creates: /etc/letsencrypt/live/{{ inventory_hostname }}/privkey.pem
  when: not privcert.stat.exists and not localprivcert.stat.exists and not selfsigned
- name: Self signed cert dir
  file:
    path: /etc/letsencrypt/live/{{ inventory_hostname }}
    state: directory
  when: not privcert.stat.exists and selfsigned and not localprivcert.stat.exists
- name: Renewal hook dir
  file:
    path: /etc/letsencrypt/renewal-hooks/deploy
    state: directory
- name: Self signed cert
  command: >
    openssl req -x509 -nodes -days 3650 -newkey rsa:2048
     -keyout /etc/letsencrypt/live/{{ inventory_hostname }}/privkey.pem
     -out /etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem
     -subj "/C=NL/ST=Noord Holland/L=Amsterdam/O=Netherlands eScience Center/CN=eWatercycle"
  args:
    creates: /etc/letsencrypt/live/{{ inventory_hostname }}/privkey.pem
  when: not privcert.stat.exists and selfsigned and not localprivcert.stat.exists
- name: CertBot build cache
  block:
  - name: Create backup folder
    delegate_to: localhost
    file:
      path: "{{ letsencrypt_backup_root }}/{{ inventory_hostname }}"
      state: directory
  - name: Synchronize letsencrypt folder
    synchronize:
      src: /etc/letsencrypt/
      dest: "{{ letsencrypt_backup_root }}/{{ inventory_hostname }}/"
      recursive: yes
      mode: pull
  when: not localprivcert.stat.exists and not selfsigned
