---
- hosts: experiments
  tasks:
    - include_role:
        name: common
    - include_role:
        name: letsencrypt
    - name: Install git, ntp and pip
      apt:
        update_cache: yes
        name: "{{ item }}"
      loop:
        - git
        - ntp
        - apt-transport-https
        - python-setuptools
        - python-pip
    - name: Home root
      file:
        path: /mnt/home
        state: directory
    - name: Apps root
      file:
        path: /mnt/apps
        state: directory
    - name: Docker
      include_role:
        name: docker
      vars:
        - docker_root: "/mnt/docker"
- hosts: cylc_server
  vars_files:
    - vars.yml
  tasks:
    - name: Docker pip
      pip:
        executable: pip
        name: "{{ item }}"
      loop:
        - docker
    - name: Forecast Docker images
      docker_image:
        name: '{{ item }}'
      with_items:
        - ewatercycle/ewatercycle_forecast_getforcing
        - ewatercycle/ewatercycle_forecast_preprocess
        - ewatercycle/ewatercycle_forecast
        - ewatercycle/ewatercycle_forecast_postprocess
    - name: Cylc
      include_role:
        name: cylc
    - name: Cylc-web
      include_role:
        name: cylc-web
    - name: Researchdrive
      include_role:
        name: researchdrive
      vars:
          researchdrive_src_dir: "{{ researchdrive.local_dir }}"
          researchdrive_dest_dir: "{{ researchdrive.remote_dir }}"
    - name: Add cylc user to researchdrive group
      user:
        name: cylc
        groups: [researchdrive]
        append: yes