---
- hosts: explore
  tasks:
    - include_role:
        name: common
    - include_role:
        name: letsencrypt
    - include_role:
        name: launcher
    - include_role:
        name: terria
    - include_role:
        name: explore-proxy
