---
- hosts: forecast
  tasks:
    - include_role:
        name: common
    - apt:
        update_cache: yes
        name: "{{ item }}"
      loop:
        - git
        - ntp
        - apt-transport-https
        - python3-setuptools
    - name: Home root
      file:
        path: /mnt/home
        state: directory
    - name: Apps root
      file:
        path: /mnt/apps
        state: directory
    - get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: /opt/get-pip.py
    - command: python3 /opt/get-pip.py
      args:
        creates: /usr/local/bin/pip3
- hosts: forecast_server
  tasks:
    - name: Allow ssh from anywhere
      ufw:
        rule: limit
        name: OpenSSH
    - name: Enable firewall
      ufw:
        state: enabled
        policy: deny
    - name: Letsencrypt
      include_role:
        name: letsencrypt
    - name: Docker
      include_role:
        name: docker
      vars:
        - docker_root: "/mnt/docker"
    - name: Forecast Web
      include_role:
        name: forecast-web
    - name: Researchdrive
      include_role:
        name: researchdrive
      vars:
          researchdrive_src_dir: "{{ researchdrive.remote_dir }}"
          researchdrive_dest_dir: "{{ researchdrive.local_dir }}"