---
- hosts: jupyter
  tasks:
    - include_role:
        name: common
    - name: Install gcc, git, ntp and pip
      apt:
        update_cache: yes
        name: "{{ item }}"
      loop:
        - git
        - gcc
        - g++
        - make
        - ntp
        - apt-transport-https
        - python3-distutils
    - name: Home root
      file:
        path: /mnt/home
        state: directory
    - name: Apps root
      file:
        path: /mnt/apps
        state: directory
    - name: Download pip installer
      get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: /opt/get-pip.py
    - name: Install latest pip
      command: python3 /opt/get-pip.py
      args:
        creates: /usr/local/bin/pip3
    - name: Docker
      include_role:
        name: docker
      vars:
        - docker_root: "/mnt/docker"
- hosts: jupyter
  tasks:
    - name: Let's encrypt cerficates
      include_role:
        name: letsencrypt
    - name: Jupyter environment
      include_role:
        name: jupyter
    - name: hymuse
      include_role:
        name: hymuse
    - name: terria
      include_role:
        name: terria
    - name: singularity
      include_role:
        name: singularity
