---
# Location where data should be uploaded from or where dCache should be mounted at
data_root: /mnt/data
dcache_url: https://webdav.grid.surfsara.nl:2880
dcache_root: '/'
dcache_rclone_name: dcache
# dCache token for mounting shared data
# Must be filled from external place like var config file or SRC
dcache_rw_token: null
# dCache token for mounting shared data
# Must be filled from external place like var config file or SRC
dcache_ro_token: null
# Location where rlcone stores it cached files
# if a storage item is attached for cache then change this var
rclone_cache_dir: /tmp/rclone
# Maximum size of rclone cache in Gigabytes
# TODO if rclone cache dir is on root disk prevent cache filling it 100% as this will cause OS problems
# TODO if free space on rclone_cache_dir is less than rclone_max_gsize then set rclone_max_gsize to available freespace
rclone_max_gsize: 45
