name: Ansible Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, grader]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Deps
      run: pip install -r requirements.txt
    - name: Lint Ansible Playbook
      run: ansible-lint --profile min --force-color research-cloud-plugin.yml populate-samba.yml
