galaxy_info:
  author: Stefan Verhoeven
  description: NGINX Web server which acts as reverse proxy and encryption.
  company: Netherlands eScience Center
  license: Apache
  min_ansible_version: 2.4
  platforms:
  - name: Ubuntu
    versions:
    - bioninc
  galaxy_tags: []
dependencies: []
