galaxy_info:
  author: Stefan Verhoeven
  description: Docker community edition installer
  company: Netherlands eScienc Center
  license: Apache
  min_ansible_version: 2.4
  platforms:
  - name: Ubuntu
    versions:
      - bionic
  galaxy_tags: []
dependencies: []
